https://drive.google.com/drive/folders/1p-RicE4Sx0Q2rqX5BbP9pl_9nSxYcbqn

In [6]:
from google.colab import files
uploaded=files.upload()

Saving machine_configurations.json to machine_configurations.json
Saving plant_master.csv to plant_master.csv
Saving manufacturing_production_120k.csv to manufacturing_production_120k.csv
Saving manufacturing_production_extra_12k.csv to manufacturing_production_extra_12k.csv
Saving machine_master.csv to machine_master.csv

In [3]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.13/dist-packages (4.0.4)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.13/dist-packages (from pyspark) (0.10.9.9)

In [4]:
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName("Tasks_23rd_Oct").getOrCreate()

**1. Load the Data in PySpark**

In [7]:
df=spark.read.csv("manufacturing_production_120k.csv",header=True,inferSchema=True)

In [8]:
df.show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [9]:
df.printSchema()

root
 |-- production_id: string (nullable = true)
 |-- production_date: date (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- operator_id: string (nullable = true)
 |-- shift: string (nullable = true)
 |-- product_code: string (nullable = true)
 |-- product_family: string (nullable = true)
 |-- units_planned: integer (nullable = true)
 |-- units_produced: integer (nullable = true)
 |-- defective_units: integer (nullable = true)
 |-- downtime_minutes: integer (nullable = true)
 |-- energy_kwh: double (nullable = true)
 |-- temperature_c: double (nullable = true)
 |-- vibration_mm_s: double (nullable = true)
 |-- quality_status: string (nullable = true)
 |-- maintenance_flag: string (nullable = true)
 |-- supervisor: string (nullable = true)

In [10]:
print(df.columns)

['production_id', 'production_date', 'plant_id', 'machine_id', 'operator_id', 'shift', 'product_code', 'product_family', 'units_planned', 'units_produced', 'defective_units', 'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s', 'quality_status', 'maintenance_flag', 'supervisor']

In [11]:
print(df.select("*").count())

120000

In [12]:
df.select("production_id","plant_id","machine_id","product_family","units_produced").show()

+-------------+--------+----------+--------------+--------------+
|production_id|plant_id|machine_id|product_family|units_produced|
+-------------+--------+----------+--------------+--------------+
|    PR0000001|    PL03|     MC011|        Motors|           993|
|    PR0000002|    PL04|     MC019|   Controllers|           836|
|    PR0000003|    PL01|     MC002|        Motors|           380|
|    PR0000004|    PL03|     MC013|         Pumps|           720|
|    PR0000005|    PL04|     MC020|         Pumps|           296|
|    PR0000006|    PL01|     MC002|        Motors|           795|
|    PR0000007|    PL02|     MC007|        Valves|           955|
|    PR0000008|    PL02|     MC009|        Valves|           895|
|    PR0000009|    PL03|     MC015|   Controllers|           289|
|    PR0000010|    PL02|     MC006|   Controllers|           527|
|    PR0000011|    PL03|     MC012|         Pumps|           512|
|    PR0000012|    PL06|     MC030|   Controllers|           968|
|    PR0000013|    PL06|     MC027|   Controllers|           867|
|    PR0000014|    PL03|     MC013|        Valves|           456|
|    PR0000015|    PL02|     MC007|        Motors|          1042|
|    PR0000016|    PL04|     MC020|   Controllers|           732|
|    PR0000017|    PL03|     MC011|   Controllers|           963|
|    PR0000018|    PL03|     MC012|        Motors|           469|
|    PR0000019|    PL01|     MC005|        Valves|           380|
|    PR0000020|    PL03|     MC014|         Pumps|           573|
+-------------+--------+----------+--------------+--------------+
only showing top 20 rows

In [13]:
print(df.dtypes)

[('production_id', 'string'), ('production_date', 'date'), ('plant_id', 'string'), ('machine_id', 'string'), ('operator_id', 'string'), ('shift', 'string'), ('product_code', 'string'), ('product_family', 'string'), ('units_planned', 'int'), ('units_produced', 'int'), ('defective_units', 'int'), ('downtime_minutes', 'int'), ('energy_kwh', 'double'), ('temperature_c', 'double'), ('vibration_mm_s', 'double'), ('quality_status', 'string'), ('maintenance_flag', 'string'), ('supervisor', 'string')]

In [14]:
sample_df=df.sample(fraction=0.5)
sample_df.show(10)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
|    PR0000021|     2026-05-08|    PL02|     MC010|     OP0362|Evening|     PMP-310|         Pumps|         1135|           994|             22|              47|    503.54|        61.64|          2.81|          Pass|              No|     Deepa|
|    PR0000023|     2026-10-15|    PL04|     MC019|     OP0187|Morning|     VLV-120|        Valves|         1031|           942|             29|              42|    268.18|         68.9|          1.92|        Reject|              No|    Bharat|
|    PR0000024|     2026-06-07|    PL03|     MC013|     OP0456|Morning|     MTR-100|        Motors|          495|           456|              3|              14|    222.03|        67.44|          3.71|        Reject|              No|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 10 rows

**2. Creating DataFrames**

In [15]:
data=[(1,"Plant A","Chennai"),(2,"Plant B","Hyderabad"),(3,"Plant C","Coimbatore")]
columns=["plant_id","plant_name","city"]
plant_small_df=spark.createDataFrame(data,columns)
plant_small_df.show()

+--------+----------+----------+
|plant_id|plant_name|      city|
+--------+----------+----------+
|       1|   Plant A|   Chennai|
|       2|   Plant B| Hyderabad|
|       3|   Plant C|Coimbatore|
+--------+----------+----------+

In [16]:
from pyspark.sql.types import *

In [17]:
schema=StructType([
    StructField("plant_id",IntegerType(),True),
    StructField("plant_name",StringType(),True),
    StructField("city",StringType(),True)
])

In [18]:
plant_struct_df=spark.createDataFrame(data,schema)
plant_struct_df.show()

+--------+----------+----------+
|plant_id|plant_name|      city|
+--------+----------+----------+
|       1|   Plant A|   Chennai|
|       2|   Plant B| Hyderabad|
|       3|   Plant C|Coimbatore|
+--------+----------+----------+

In [19]:
plant_struct_df.printSchema()

root
 |-- plant_id: integer (nullable = true)
 |-- plant_name: string (nullable = true)
 |-- city: string (nullable = true)

In [20]:
from pyspark.sql import functions as F

In [21]:
plant_struct_df=plant_struct_df.withColumn(
    "country",
    F.lit("India")
)
plant_struct_df.show()

+--------+----------+----------+-------+
|plant_id|plant_name|      city|country|
+--------+----------+----------+-------+
|       1|   Plant A|   Chennai|  India|
|       2|   Plant B| Hyderabad|  India|
|       3|   Plant C|Coimbatore|  India|
+--------+----------+----------+-------+

**3. Pandas DataFrame**

In [22]:
import pandas as pd
pdf = pd.read_csv("manufacturing_production_120k.csv")

In [23]:
pdf.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

In [24]:
pdf.tail()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
119995,PR0119996,2026-07-13,PL05,MC022,OP0193,Evening,MTR-200,Motors,435,399,1,73.0,126.07,62.79,5.73,Rework,No,Bharat
119996,PR0119997,2026-04-26,PL05,MC024,OP0124,Evening,CTL-130,Controllers,813,777,8,49.0,318.22,63.05,3.53,Pass,No,Irfan
119997,PR0119998,2026-02-01,PL06,MC027,OP0051,Evening,VLV-120,Valves,650,597,13,0.0,269.46,60.52,3.81,Pass,No,Bharat
119998,PR0119999,2026-01-17,PL01,MC001,OP0452,Evening,MTR-300,Motors,887,899,22,21.0,184.62,64.89,5.20,Pass,Yes,Farah
119999,PR0120000,2026-08-16,PL02,MC007,OP0420,Morning,MTR-200,Motors,547,477,4,43.0,107.95,62.50,3.97,Pass,No,Farah

In [25]:
pdf.shape

(120000, 18)

In [26]:
pdf.columns

Index(['production_id', 'production_date', 'plant_id', 'machine_id',
       'operator_id', 'shift', 'product_code', 'product_family',
       'units_planned', 'units_produced', 'defective_units',
       'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s',
       'quality_status', 'maintenance_flag', 'supervisor'],
      dtype='object')

In [27]:
pdf.dtypes

production_id        object
production_date      object
plant_id             object
machine_id           object
operator_id          object
shift                object
product_code         object
product_family       object
units_planned         int64
units_produced        int64
defective_units       int64
downtime_minutes    float64
energy_kwh          float64
temperature_c       float64
vibration_mm_s      float64
quality_status       object
maintenance_flag     object
supervisor           object
dtype: object

In [28]:
print(pdf[["plant_id","machine_id","units_produced"]])

       plant_id machine_id  units_produced
0          PL03      MC011             993
1          PL04      MC019             836
2          PL01      MC002             380
3          PL03      MC013             720
4          PL04      MC020             296
...         ...        ...             ...
119995     PL05      MC022             399
119996     PL05      MC024             777
119997     PL06      MC027             597
119998     PL01      MC001             899
119999     PL02      MC007             477

[120000 rows x 3 columns]

In [29]:
renamed_pdf=pdf.rename(columns={"units_produced":"production_output"})
renamed_pdf.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,production_output,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

In [30]:
print(pdf[pdf["quality_status"]=="Reject"])

       production_id production_date plant_id machine_id operator_id    shift  \
1          PR0000002      2026-08-03     PL04      MC019      OP0489  Morning
2          PR0000003      2026-05-20     PL01      MC002      OP0189  Evening
7          PR0000008      2026-08-17     PL02      MC009      OP0106    Night
9          PR0000010      2026-02-13     PL02      MC006      OP0593  Evening
21         PR0000022      2026-03-03     PL02      MC009      OP0294  Evening
...              ...             ...      ...        ...         ...      ...
119979     PR0119980      2026-07-21     PL02      MC006      OP0591  Morning
119988     PR0119989      2026-01-29     PL01      MC003      OP0021    Night
119989     PR0119990      2026-07-20     PL06      MC027      OP0217  Evening
119991     PR0119992      2026-04-07     PL05      MC024      OP0186  Morning
119994     PR0119995      2026-09-29     PL03      MC013      OP0151  Evening

       product_code product_family  units_planned  units_produced  \
1           CTL-330    Controllers            809             836
2           MTR-300         Motors            442             380
7           VLV-320         Valves            862             895
9           CTL-230    Controllers            532             527
21          MTR-300         Motors            623             560
...             ...            ...            ...             ...
119979      VLV-320         Valves           1149            1036
119988      PMP-310          Pumps           1195            1053
119989      CTL-230    Controllers            782             796
119991      PMP-310          Pumps           1187            1024
119994      CTL-330    Controllers            983            1010

        defective_units  downtime_minutes  energy_kwh  temperature_c  \
1                     0               0.0      398.58          64.37
2                    17              15.0      183.34          54.13
7                    51              77.0      266.06          57.10
9                    26              64.0      112.17          60.96
21                   23              14.0      217.69          55.23
...                 ...               ...         ...            ...
119979               48              40.0      316.55          70.09
119988               26              72.0      240.94          62.27
119989               10              71.0      150.47          66.59
119991               35              32.0      486.71          54.09
119994               25              74.0      199.71          69.71

        vibration_mm_s quality_status maintenance_flag supervisor
1                 2.28         Reject               No      Farah
2                 4.66         Reject               No      Deepa
7                 1.34         Reject               No      Irfan
9                 3.48         Reject               No      Gopal
21                3.28         Reject              Yes      Farah
...                ...            ...              ...        ...
119979            2.90         Reject               No     Harini
119988            4.93         Reject               No      Farah
119989            4.08         Reject               No     Bharat
119991            3.37         Reject               No      Farah
119994            3.65         Reject              Yes      Farah

[22744 rows x 18 columns]

In [31]:
print(pdf[pdf["temperature_c"]>75])

       production_id production_date plant_id machine_id operator_id    shift  \
14         PR0000015      2026-03-15     PL02      MC007      OP0238  Morning
16         PR0000017      2026-08-04     PL03      MC011      OP0533  Morning
19         PR0000020      2026-02-18     PL03      MC014      OP0563  Morning
26         PR0000027      2026-01-03     PL05      MC023      OP0190  Morning
54         PR0000055      2026-07-31     PL01      MC005      OP0212  Morning
...              ...             ...      ...        ...         ...      ...
119767     PR0119768      2026-01-29     PL02      MC007      OP0262  Evening
119810     PR0119811      2026-07-09     PL05      MC024      OP0372  Evening
119833     PR0119834      2026-06-22     PL04      MC020      OP0038  Morning
119848     PR0119849      2026-02-25     PL06      MC027      OP0563  Morning
119968     PR0119969      2026-06-05     PL05      MC022      OP0366    Night

       product_code product_family  units_planned  units_produced  \
14          MTR-300         Motors           1086            1042
16          CTL-330    Controllers           1152             963
19          PMP-310          Pumps            646             573
26          PMP-210          Pumps            358             310
54          CTL-230    Controllers            499             478
...             ...            ...            ...             ...
119767      CTL-130    Controllers           1129            1139
119810      CTL-230    Controllers            819             687
119833      CTL-330    Controllers            749             669
119848      PMP-310          Pumps            925             816
119968      MTR-200         Motors            273             227

        defective_units  downtime_minutes  energy_kwh  temperature_c  \
14                    4             172.0      239.64          76.39
16                   28              91.0      347.34          75.09
19                   13              64.0      277.73          76.92
26                    6              46.0       78.29          75.42
54                   10              32.0      112.60          75.10
...                 ...               ...         ...            ...
119767                0              30.0      362.12          77.17
119810               45              50.0      171.84          75.24
119833               12              46.0      291.22          80.53
119848               28               0.0      258.03          75.94
119968                0              48.0       55.44          77.04

        vibration_mm_s quality_status maintenance_flag supervisor
14                2.81           Pass               No      Deepa
16                4.00           Pass              Yes      Gopal
19                2.35           Pass               No      Irfan
26                3.72         Rework               No      Anita
54                3.38           Pass               No      Farah
...                ...            ...              ...        ...
119767            1.98           Pass               No      Anita
119810            4.17         Reject               No     Bharat
119833            3.05           Pass               No      Anita
119848            3.53         Rework               No     Charan
119968             NaN           Pass               No     Harini

[6505 rows x 18 columns]

In [32]:
print(pdf[pdf["shift"]=="Night"])

       production_id production_date plant_id machine_id operator_id  shift  \
7          PR0000008      2026-08-17     PL02      MC009      OP0106  Night
10         PR0000011      2026-09-29     PL03      MC012      OP0141  Night
12         PR0000013      2026-07-19     PL06      MC027      OP0172  Night
28         PR0000029      2026-04-30     PL05      MC023      OP0339  Night
29         PR0000030      2026-09-18     PL01      MC004      OP0266  Night
...              ...             ...      ...        ...         ...    ...
119982     PR0119983      2026-08-10     PL03      MC013      OP0579  Night
119985     PR0119986      2026-06-22     PL04      MC016      OP0543  Night
119986     PR0119987      2026-06-10     PL05      MC025      OP0346  Night
119987     PR0119988      2026-08-18     PL04      MC016      OP0142  Night
119988     PR0119989      2026-01-29     PL01      MC003      OP0021  Night

       product_code product_family  units_planned  units_produced  \
7           VLV-320         Valves            862             895
10          PMP-210          Pumps            577             512
12          CTL-330    Controllers           1004             867
28          VLV-120         Valves            987            1010
29          VLV-320         Valves            358             359
...             ...            ...            ...             ...
119982      VLV-320         Valves           1064            1068
119985      MTR-300         Motors            306             308
119986      CTL-130    Controllers            840             868
119987      CTL-330    Controllers            633             625
119988      PMP-310          Pumps           1195            1053

        defective_units  downtime_minutes  energy_kwh  temperature_c  \
7                    51              77.0      266.06          57.10
10                   14              32.0      127.00          52.81
12                   27              66.0      388.61          50.88
28                   25              53.0      199.38          65.76
29                    1              19.0      107.98          72.00
...                 ...               ...         ...            ...
119982               36              24.0      512.37          71.12
119985               13              24.0      113.47          57.18
119986               28              53.0      213.56          65.84
119987               20              65.0      161.84          59.92
119988               26              72.0      240.94          62.27

        vibration_mm_s quality_status maintenance_flag supervisor
7                 1.34         Reject               No      Irfan
10                3.46           Pass               No     Bharat
12                5.70           Pass              Yes      Deepa
28                4.48         Reject               No     Harini
29                1.73           Pass               No     Bharat
...                ...            ...              ...        ...
119982            2.20           Pass               No     Harini
119985            5.04           Pass               No      Deepa
119986            3.44           Pass               No     Charan
119987            4.81           Pass               No     Bharat
119988            4.93         Reject               No      Farah

[40307 rows x 18 columns]

**4. Dask DataFrame**

In [33]:
import dask.dataframe as dd
ddf = dd.read_csv(
"manufacturing_production_120k.csv",assume_missing=True
)

In [34]:
print(ddf.head())

  production_id production_date plant_id machine_id operator_id    shift  \
0     PR0000001      2026-08-07     PL03      MC011      OP0275  Evening
1     PR0000002      2026-08-03     PL04      MC019      OP0489  Morning
2     PR0000003      2026-05-20     PL01      MC002      OP0189  Evening
3     PR0000004      2026-01-15     PL03      MC013      OP0076  Morning
4     PR0000005      2026-09-21     PL04      MC020      OP0501  Morning

  product_code product_family  units_planned  units_produced  defective_units  \
0      MTR-100         Motors         1060.0           993.0             30.0
1      CTL-330    Controllers          809.0           836.0              0.0
2      MTR-300         Motors          442.0           380.0             17.0
3      PMP-210          Pumps          787.0           720.0              7.0
4      PMP-110          Pumps          344.0           296.0              7.0

   downtime_minutes  energy_kwh  temperature_c  vibration_mm_s quality_status  \
0              34.0      388.11          61.40            3.88         Rework
1               0.0      398.58          64.37            2.28         Reject
2              15.0      183.34          54.13            4.66         Reject
3              39.0      217.61          64.47             NaN         Rework
4              49.0      115.47          72.59            3.21           Pass

  maintenance_flag supervisor
0               No     Charan
1               No      Farah
2               No      Deepa
3               No      Farah
4               No      Deepa

In [35]:
print(ddf.npartitions)

1

In [36]:
selected=ddf[["plant_id","product_family","units_produced"]]
print(selected.head())

  plant_id product_family  units_produced
0     PL03         Motors           993.0
1     PL04    Controllers           836.0
2     PL01         Motors           380.0
3     PL03          Pumps           720.0
4     PL04          Pumps           296.0

In [37]:
print(ddf[ddf["quality_status"]=="Reject"].head())

   production_id production_date plant_id machine_id operator_id    shift  \
1      PR0000002      2026-08-03     PL04      MC019      OP0489  Morning
2      PR0000003      2026-05-20     PL01      MC002      OP0189  Evening
7      PR0000008      2026-08-17     PL02      MC009      OP0106    Night
9      PR0000010      2026-02-13     PL02      MC006      OP0593  Evening
21     PR0000022      2026-03-03     PL02      MC009      OP0294  Evening

   product_code product_family  units_planned  units_produced  \
1       CTL-330    Controllers          809.0           836.0
2       MTR-300         Motors          442.0           380.0
7       VLV-320         Valves          862.0           895.0
9       CTL-230    Controllers          532.0           527.0
21      MTR-300         Motors          623.0           560.0

    defective_units  downtime_minutes  energy_kwh  temperature_c  \
1               0.0               0.0      398.58          64.37
2              17.0              15.0      183.34          54.13
7              51.0              77.0      266.06          57.10
9              26.0              64.0      112.17          60.96
21             23.0              14.0      217.69          55.23

    vibration_mm_s quality_status maintenance_flag supervisor
1             2.28         Reject               No      Farah
2             4.66         Reject               No      Deepa
7             1.34         Reject               No      Irfan
9             3.48         Reject               No      Gopal
21            3.28         Reject              Yes      Farah

In [38]:
avg_units=ddf.groupby("plant_id")["units_produced"].mean()
print(avg_units.compute())

plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64

In [39]:
total_defects=ddf.groupby("product_family")["defective_units"].sum()
print(total_defects.compute())

product_family
Controllers    507781.0
Motors         505287.0
Pumps          507864.0
Valves         509312.0
Name: defective_units, dtype: float64

In [40]:
pavg_units=pdf.groupby("plant_id")["units_produced"].mean()
print("Pandas:")
print(pavg_units)
davg_units=ddf.groupby("plant_id")["units_produced"].mean().compute()
print("Dask:")
print(davg_units)

Pandas:
plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64
Dask:
plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64

**5. Manipulating DataFrames**

In [41]:
transformed_df=df.withColumn(
    "production_efficiency",
    F.when(F.col("units_planned")!=0,
           F.col("units_produced")/F.col("units_planned")*100)
).withColumn(
    "good_units",
    F.col("units_produced")-F.col("defective_units")
).withColumn(
    "country",
    F.lit("India")
).withColumnRenamed(
    "energy_kwh","energy_consumed"
).withColumn(
    "units_produced",
    F.col("units_produced").cast("double")
).withColumn(
    "defect_percentage",
    F.when(
        F.col("units_produced") != 0,
        F.col("defective_units") / F.col("units_produced") * 100
    )
).withColumn(
    "energy_per_unit",
    F.when(
        F.col("units_produced") != 0,
        F.col("energy_consumed") / F.col("units_produced")
    )
)

transformed_df.select(
    "production_efficiency",
    "good_units",
    "country",
    "energy_consumed",
    "units_produced",
    "defect_percentage",
    "energy_per_unit"
).show()

+---------------------+----------+-------+---------------+--------------+------------------+-------------------+
|production_efficiency|good_units|country|energy_consumed|units_produced| defect_percentage|    energy_per_unit|
+---------------------+----------+-------+---------------+--------------+------------------+-------------------+
|    93.67924528301886|       963|  India|         388.11|         993.0|3.0211480362537766|0.39084592145015107|
|   103.33745364647713|       836|  India|         398.58|         836.0|               0.0| 0.4767703349282296|
|    85.97285067873304|       363|  India|         183.34|         380.0| 4.473684210526316|0.48247368421052633|
|     91.4866581956798|       713|  India|         217.61|         720.0|0.9722222222222222|0.30223611111111115|
|    86.04651162790698|       289|  India|         115.47|         296.0| 2.364864864864865| 0.3901013513513513|
|    82.98538622129436|       745|  India|         290.26|         795.0| 6.289308176100629| 0.3651069182389937|
|    81.97424892703863|       945|  India|         355.56|         955.0|1.0471204188481675|0.37231413612565445|
|   103.82830626450117|       844|  India|         266.06|         895.0| 5.698324022346369| 0.2972737430167598|
|    92.33226837060703|       281|  India|          87.62|         289.0| 2.768166089965398| 0.3031833910034602|
|    99.06015037593986|       501|  India|         112.17|         527.0| 4.933586337760911| 0.2128462998102467|
|    88.73483535528595|       498|  India|          127.0|         512.0|          2.734375|        0.248046875|
|    98.77551020408163|       945|  India|         377.97|         968.0|  2.37603305785124| 0.3904648760330579|
|    86.35458167330677|       840|  India|         388.61|         867.0|3.1141868512110724| 0.4482237600922722|
|   101.78571428571428|       450|  India|         108.83|         456.0|1.3157894736842104|0.23866228070175438|
|    95.94843462246777|      1038|  India|         239.64|        1042.0|0.3838771593090211|0.22998080614203453|
|    84.13793103448276|       732|  India|         289.55|         732.0|               0.0| 0.3955601092896175|
|             83.59375|       935|  India|         347.34|         963.0| 2.907580477673936|0.36068535825545167|
|    86.69131238447319|       451|  India|         241.05|         469.0|3.8379530916844353| 0.5139658848614073|
|    99.73753280839895|       364|  India|         137.99|         380.0|4.2105263157894735|0.36313157894736847|
|    88.69969040247679|       560|  India|         277.73|         573.0|2.2687609075043627|  0.484694589877836|
+---------------------+----------+-------+---------------+--------------+------------------+-------------------+
only showing top 20 rows

**6. Dropping Data**

In [42]:
df.drop("supervisor").show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
only showing top 20 rows

In [43]:
df.drop("supervisor","maintenance_flag").show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
only showing top 20 rows

In [44]:
df.dropDuplicates().show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000304|     2026-07-31|    PL01|     MC004|     OP0518|Evening|     MTR-200|        Motors|          339|           288|              0|              57|     83.44|        58.53|          1.47|          Pass|              No|    Bharat|
|    PR0000408|     2026-08-07|    PL06|     MC028|     OP0616|Evening|     PMP-110|         Pumps|          814|           772|             23|              67|    305.59|        54.17|          4.68|          Pass|              No|    Charan|
|    PR0000485|     2026-10-06|    PL01|     MC001|     OP0494|Morning|     VLV-220|        Valves|          756|           695|             16|               0|    283.91|        70.56|          3.65|          Pass|             Yes|     Deepa|
|    PR0000621|     2026-05-02|    PL06|     MC027|     OP0622|Evening|     VLV-220|        Valves|          440|           370|             17|               0|    156.23|        58.35|          3.97|        Reject|              No|    Bharat|
|    PR0000699|     2026-06-06|    PL01|     MC002|     OP0555|  Night|     CTL-230|   Controllers|         1014|           875|             31|              30|    251.46|         70.3|           0.4|          Pass|              No|     Deepa|
|    PR0000901|     2026-06-26|    PL03|     MC011|     OP0212|Evening|     CTL-330|   Controllers|         1041|           871|              8|              10|    338.52|        82.76|           3.9|        Rework|             Yes|     Farah|
|    PR0000928|     2026-04-11|    PL05|     MC022|     OP0448|  Night|     CTL-130|   Controllers|         1097|           950|              9|              38|    465.35|        58.71|          4.95|        Reject|              No|    Charan|
|    PR0001046|     2026-03-22|    PL06|     MC028|     OP0398|Morning|     MTR-300|        Motors|          508|           474|             21|              36|    127.29|        59.15|          4.97|          Pass|              No|     Gopal|
|    PR0001604|     2026-08-21|    PL03|     MC011|     OP0545|Evening|     CTL-230|   Controllers|          313|           268|              0|              52|    115.27|        57.78|          4.43|          Pass|              No|    Harini|
|    PR0001616|     2026-06-11|    PL04|     MC019|     OP0281|  Night|     PMP-210|         Pumps|          344|           307|             20|              27|    116.84|        64.66|          3.06|        Rework|              No|     Deepa|
|    PR0001787|     2026-02-27|    PL02|     MC009|     OP0520|Evening|     MTR-200|        Motors|          878|           803|             16|              49|    262.41|        68.62|          4.23|        Reject|             Yes|    Bharat|
|    PR0002111|     2026-01-10|    PL06|     MC030|     OP0216|Morning|     PMP-110|         Pumps|          399|           350|             12|              17|    152.95|        66.18|          2.62|          Pass|              No|     Deepa|
|    PR0002144|     2026-01-21|    PL01|     MC002|     OP0447|Evening|     VLV-120|        Valves|          327|           272|             11|              35|     90.76|        60.29|          1.87|        Rework|              No|     Gopal|
|    PR0002226|     2026-03-04|    PL03|     MC011|     OP0575|  Night|     MTR-100|        Motors|         1134|          1147|              0|               0|    526.95|        49.78|          2.95|        Reject|             Yes|    Harini|
|    PR0002276|     2026-07-15|    PL02|     MC010|     OP0518|Morning|     CTL-130|   Controllers|         1047|           928|              4|               0|    192.77|        77.85|          2.59|        Reject|              No|    Bharat|
|    PR0002423|     2026-10-22|    PL03|     MC013|     OP0193|  Night|     PMP-210|         Pumps|         1064|          1004|             14|              34|    342.26|        48.96|          1.32|          Pass|              No|    Harini|
|    PR0002632|     2026-08-27|    PL06|     MC030|     OP0483|  Night|     PMP-210|         Pumps|          279|           244|              6|               6|      63.8|        53.44|           1.9|          Pass|             Yes|    Bharat|
|    PR0002883|     2026-09-16|    PL04|     MC019|     OP0553|Morning|     CTL-330|   Controllers|          603|           620|             25|              15|    282.94|        75.99|          4.35|        Rework|              No|     Deepa|
|    PR0002899|     2026-07-21|    PL06|     MC028|     OP0258|  Night|     MTR-200|        Motors|          790|           747|             11|              15|     340.8|        75.33|          3.71|          Pass|              No|    Harini|
|    PR0003156|     2026-04-19|    PL05|     MC025|     OP0524|Evening|     CTL-130|   Controllers|          700|           721|             22|             142|    159.02|        59.89|          4.79|          Pass|              No|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [45]:
df.dropDuplicates(["production_id"]).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000025|     2026-07-28|    PL04|     MC017|     OP0636|Evening|     VLV-220|        Valves|         1139|          1126|             38|              13|    332.97|        58.08|          4.15|          Pass|              No|     Irfan|
|    PR0000026|     2026-04-09|    PL01|     MC001|     OP0604|Evening|     MTR-300|        Motors|          643|           663|             20|              26|    180.36|        63.77|          4.49|          Pass|             Yes|    Charan|
|    PR0000031|     2026-01-04|    PL01|     MC003|     OP0524|Evening|     PMP-210|         Pumps|          762|           776|             49|              28|    238.12|         66.8|          3.09|        Reject|              No|    Bharat|
|    PR0000032|     2026-05-28|    PL06|     MC030|     OP0074|  Night|     CTL-230|   Controllers|          819|           773|             11|              27|     354.3|        63.51|          3.18|          Pass|              No|     Deepa|
|    PR0000036|     2026-07-13|    PL04|     MC020|     OP0559|Evening|     MTR-200|        Motors|          576|           578|              0|              38|    267.36|        70.28|          2.69|          Pass|              No|     Farah|
|    PR0000037|     2026-10-12|    PL06|     MC026|     OP0163|Morning|     MTR-100|        Motors|          633|           626|             15|              56|    173.17|        64.63|           3.7|          Pass|              No|     Irfan|
|    PR0000038|     2026-02-23|    PL02|     MC008|     OP0114|  Night|     MTR-300|        Motors|          864|           867|              6|              38|    335.24|         53.7|           3.0|          Pass|              No|     Anita|
|    PR0000039|     2026-07-17|    PL01|     MC002|     OP0220|  Night|     VLV-120|        Valves|          260|           265|              0|               2|    127.18|        51.87|          3.41|          Pass|              No|     Irfan|
|    PR0000041|     2026-05-14|    PL02|     MC009|     OP0192|Morning|     PMP-310|         Pumps|          711|           664|             32|              60|    335.84|        57.87|           3.2|          Pass|             Yes|     Irfan|
|    PR0000046|     2026-04-02|    PL06|     MC027|     OP0484|Morning|     VLV-120|        Valves|          847|           778|             19|             145|    381.88|        63.42|          2.94|        Reject|              No|     Anita|
|    PR0000047|     2026-01-22|    PL06|     MC028|     OP0512|Evening|     PMP-110|         Pumps|          956|           882|              4|             118|     247.4|         NULL|          2.52|          Pass|              No|    Charan|
|    PR0000048|     2026-03-08|    PL03|     MC015|     OP0110|Morning|     CTL-230|   Controllers|          858|           810|              0|               0|    250.54|        58.93|          4.04|          Pass|              No|    Bharat|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [46]:
df.filter(
    (F.col("operator_ID").isNotNull()) &
    (F.trim(F.col("operator_ID"))!="")
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [47]:
df.na.drop(
    how="all",
    subset=["temperature_c","vibration_mm_s"]
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [48]:
df.select("product_family").distinct().show()

+--------------+
|product_family|
+--------------+
|         Pumps|
|        Valves|
|   Controllers|
|        Motors|
+--------------+

In [49]:
df.select("plant_id","machine_id").distinct().show()

+--------+----------+
|plant_id|machine_id|
+--------+----------+
|    PL01|     MC001|
|    PL01|     MC004|
|    PL04|     MC019|
|    PL04|     MC017|
|    PL05|     MC022|
|    PL04|     MC018|
|    PL01|     MC003|
|    PL06|     MC029|
|    PL02|     MC007|
|    PL03|     MC013|
|    PL06|     MC030|
|    PL04|     MC020|
|    PL05|     MC021|
|    PL01|     MC005|
|    PL02|     MC010|
|    PL04|     MC016|
|    PL06|     MC027|
|    PL02|     MC006|
|    PL01|     MC002|
|    PL06|     MC028|
+--------+----------+
only showing top 20 rows

**7. Sorting**

In [50]:
df.sort(F.col("units_produced").asc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|
|    PR0059668|     2026-05-01|    PL05|     MC021|     OP0067|  Night|     CTL-130|   Controllers|          250|           205|             11|              54|     89.67|        58.31|          2.69|          Pass|              No|     Anita|
|    PR0079337|     2026-05-05|    PL04|     MC018|     OP0623|Evening|     PMP-210|         Pumps|          251|           206|              0|               0|     77.66|        67.78|          2.36|        Rework|              No|     Irfan|
|    PR0013719|     2026-04-30|    PL03|     MC014|     OP0340|Morning|     MTR-200|        Motors|          250|           206|              5|              82|     62.29|        55.57|           2.4|          Pass|              No|    Harini|
|    PR0087182|     2026-09-03|    PL04|     MC019|     OP0196|Evening|     CTL-330|   Controllers|          250|           206|              4|              13|     98.25|        59.27|          6.99|        Reject|             Yes|     Irfan|
|    PR0015709|     2026-03-09|    PL05|     MC021|     OP0538|  Night|     VLV-220|        Valves|          251|           206|              9|               3|     87.29|        68.35|          1.27|        Reject|              No|    Bharat|
|    PR0115075|     2026-10-03|    PL04|     MC019|     OP0014|  Night|     CTL-130|   Controllers|          251|           206|              1|              66|     79.31|         78.2|          4.21|        Rework|              No|    Bharat|
|    PR0026161|     2026-04-28|    PL05|     MC025|     OP0617|Evening|     PMP-210|         Pumps|          251|           206|              2|              42|     74.72|        76.08|          3.96|        Reject|             Yes|     Gopal|
|    PR0030899|     2026-05-24|    PL01|     MC004|     OP0380|Evening|     VLV-120|        Valves|          252|           206|             12|              12|     75.94|        50.77|          3.34|        Rework|              No|     Farah|
|    PR0039880|     2026-01-04|    PL01|     MC005|     OP0034|Evening|     PMP-210|         Pumps|          250|           206|              0|              38|      50.0|        64.38|          2.33|        Rework|              No|     Deepa|
|    PR0071924|     2026-05-26|    PL01|     MC003|     OP0120|  Night|     PMP-210|         Pumps|          251|           206|              9|              40|      50.0|        52.13|          2.54|          Pass|              No|     Irfan|
|    PR0107410|     2026-09-29|    PL03|     MC012|     OP0237|Evening|     VLV-120|        Valves|          252|           207|              8|              36|     99.97|        61.39|          3.94|          Pass|              No|     Deepa|
|    PR0013195|     2026-03-18|    PL05|     MC021|     OP0182|  Night|     PMP-310|         Pumps|          253|           207|              4|              18|     59.88|        73.69|          2.98|          Pass|              No|     Irfan|
|    PR0118888|     2026-06-01|    PL04|     MC019|     OP0350|Morning|     MTR-300|        Motors|          250|           207|              3|              29|      50.0|        53.55|          4.18|          Pass|              No|     Farah|
|    PR0020293|     2026-08-08|    PL03|     MC014|     OP0567|Evening|     CTL-130|   Controllers|          253|           207|              5|              37|      50.0|        64.89|          1.81|          Pass|              No|     Deepa|
|    PR0028542|     2026-04-10|    PL04|     MC020|     OP0325|Evening|     CTL-230|   Controllers|          251|           207|              8|              18|     93.84|         64.9|          1.55|          Pass|              No|     Anita|
|    PR0035230|     2026-02-05|    PL06|     MC029|     OP0479|  Night|     VLV-120|        Valves|          253|           207|              6|               0|    107.62|         NULL|          3.56|        Rework|              No|     Anita|
|    PR0097162|     2026-09-02|    PL06|     MC027|     OP0139|  Night|     MTR-100|        Motors|          252|           208|              6|              11|     92.62|        61.86|          1.74|          Pass|              No|     Deepa|
|    PR0005895|     2026-09-15|    PL04|     MC018|     OP0322|  Night|     VLV-320|        Valves|          251|           208|              3|              33|     66.87|        49.32|          2.91|          Pass|              No|    Bharat|
|    PR0105232|     2026-08-26|    PL04|     MC018|     OP0505|Evening|     VLV-220|        Valves|          251|           208|              8|               0|      59.1|        57.55|          3.65|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [51]:
df.sort(F.col("units_produced").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0074297|     2026-05-20|    PL04|     MC019|     OP0142|Morning|     MTR-200|        Motors|         1195|          1238|             23|               0|     331.2|        66.75|           4.1|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [52]:
df.sort(F.col("defective_units").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0051359|     2026-09-16|    PL02|     MC009|     OP0181|Morning|     CTL-230|   Controllers|         1192|          1230|            108|               8|    555.34|        71.97|          2.09|        Rework|              No|     Irfan|
|    PR0108009|     2026-06-07|    PL05|     MC023|     OP0417|Morning|     CTL-230|   Controllers|         1061|          1067|            106|               0|    491.74|         NULL|          4.93|        Rework|             Yes|     Farah|
|    PR0067365|     2026-05-13|    PL01|     MC001|     OP0461|Evening|     MTR-100|        Motors|         1189|          1186|            103|               0|    373.15|        64.44|          4.27|        Reject|             Yes|     Farah|
|    PR0070440|     2026-05-23|    PL04|     MC018|     OP0033|  Night|     VLV-120|        Valves|         1133|          1124|            102|               0|    238.46|        71.28|          2.79|        Reject|              No|     Deepa|
|    PR0082514|     2026-03-18|    PL04|     MC017|     OP0007|Morning|     PMP-310|         Pumps|         1181|          1109|            100|              19|    331.99|        56.53|          2.97|        Reject|              No|     Anita|
|    PR0106744|     2026-04-27|    PL01|     MC003|     OP0094|Evening|     CTL-130|   Controllers|         1084|          1103|            100|               0|    465.02|        68.15|          2.18|        Rework|              No|    Charan|
|    PR0013103|     2026-05-06|    PL02|     MC009|     OP0159|Morning|     MTR-100|        Motors|         1042|           990|             97|              30|    196.72|        57.62|          3.46|        Rework|              No|    Harini|
|    PR0045241|     2026-01-04|    PL03|     MC013|     OP0202|Morning|     VLV-320|        Valves|         1197|          1231|             96|              23|    456.16|         63.5|          1.55|        Rework|              No|    Harini|
|    PR0103867|     2026-06-07|    PL04|     MC017|     OP0033|Morning|     PMP-310|         Pumps|         1088|          1095|             95|              29|    411.22|        62.63|           0.4|        Rework|              No|     Irfan|
|    PR0043427|     2026-02-04|    PL04|     MC017|     OP0003|Morning|     VLV-120|        Valves|         1170|          1196|             95|              19|    218.83|        65.99|          NULL|        Rework|              No|     Deepa|
|    PR0068424|     2026-07-18|    PL06|     MC027|     OP0609|Evening|     VLV-320|        Valves|         1052|          1073|             93|              52|    406.85|         57.3|          4.71|        Reject|             Yes|    Harini|
|    PR0014350|     2026-09-27|    PL05|     MC023|     OP0458|Evening|     CTL-330|   Controllers|         1120|          1128|             91|               7|    250.83|        61.73|          4.66|        Rework|              No|     Farah|
|    PR0068990|     2026-02-02|    PL01|     MC004|     OP0210|Evening|     CTL-230|   Controllers|         1136|          1104|             91|              47|    232.35|        61.59|          3.57|        Reject|              No|     Farah|
|    PR0078536|     2026-05-11|    PL03|     MC012|     OP0486|  Night|     PMP-110|         Pumps|         1141|          1095|             91|              51|    301.78|        62.09|          3.48|        Rework|              No|     Farah|
|    PR0039878|     2026-07-28|    PL05|     MC022|     OP0464|Evening|     MTR-100|        Motors|         1052|           990|             90|              14|    341.79|        57.54|           3.7|        Reject|              No|    Charan|
|    PR0082255|     2026-09-01|    PL02|     MC007|     OP0528|  Night|     VLV-320|        Valves|         1174|          1123|             89|              20|    314.99|        71.07|          0.83|        Rework|              No|     Gopal|
|    PR0085319|     2026-09-23|    PL05|     MC024|     OP0399|Morning|     VLV-120|        Valves|          973|           970|             89|              52|    390.03|         59.4|          1.64|        Rework|             Yes|     Irfan|
|    PR0027472|     2026-10-22|    PL04|     MC016|     OP0340|Morning|     CTL-330|   Controllers|         1100|           960|             88|              40|    341.48|        51.33|          4.22|        Rework|              No|    Harini|
|    PR0116375|     2026-01-06|    PL03|     MC015|     OP0318|  Night|     MTR-200|        Motors|         1174|          1206|             88|              68|    405.22|        57.62|          4.43|        Rework|              No|     Farah|
|    PR0064147|     2026-07-28|    PL01|     MC004|     OP0105|Evening|     MTR-100|        Motors|         1162|          1159|             88|               0|    297.53|        58.15|           0.4|        Rework|              No|     Gopal|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [53]:
df.sort("plant_id",F.col("units_produced").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|
|    PR0006350|     2026-02-04|    PL01|     MC004|     OP0322|  Night|     PMP-110|         Pumps|         1193|          1234|             38|              27|    585.43|        59.48|          2.58|          Pass|             Yes|     Anita|
|    PR0046906|     2026-04-21|    PL01|     MC005|     OP0649|Evening|     CTL-230|   Controllers|         1199|          1233|             75|              42|    392.44|        69.03|          2.04|        Reject|             Yes|     Gopal|
|    PR0046582|     2026-07-18|    PL01|     MC002|     OP0040|  Night|     MTR-100|        Motors|         1190|          1230|              3|              34|    232.68|        51.69|          4.69|        Reject|              No|     Irfan|
|    PR0097172|     2026-01-29|    PL01|     MC002|     OP0257|  Night|     PMP-310|         Pumps|         1198|          1229|             55|              30|    444.46|        71.27|          4.99|        Rework|              No|     Deepa|
|    PR0024941|     2026-04-21|    PL01|     MC002|     OP0101|Evening|     VLV-120|        Valves|         1193|          1229|             25|             117|    310.61|        65.69|          2.64|        Reject|              No|    Harini|
|    PR0088933|     2026-03-04|    PL01|     MC003|     OP0492|Morning|     MTR-300|        Motors|         1190|          1229|             51|              34|    267.82|        78.75|          4.76|        Rework|              No|    Bharat|
|    PR0048075|     2026-03-05|    PL01|     MC005|     OP0171|Evening|     PMP-310|         Pumps|         1196|          1228|             14|              12|    569.62|        54.97|          4.02|          Pass|              No|    Harini|
|    PR0083644|     2026-07-13|    PL01|     MC005|     OP0043|Evening|     PMP-310|         Pumps|         1188|          1228|             16|              30|    533.46|        70.21|          4.53|          Pass|              No|    Bharat|
|    PR0002284|     2026-08-31|    PL01|     MC004|     OP0639|Evening|     PMP-110|         Pumps|         1192|          1227|             30|               0|    438.15|        66.08|          3.65|        Rework|              No|     Farah|
|    PR0109962|     2026-03-06|    PL01|     MC001|     OP0536|Evening|     MTR-300|        Motors|         1199|          1227|             16|              15|    280.96|        52.32|          2.04|          Pass|              No|     Gopal|
|    PR0012821|     2026-07-14|    PL01|     MC005|     OP0195|Morning|     CTL-130|   Controllers|         1192|          1226|              7|              58|     625.8|        57.83|          2.22|        Reject|              No|     Farah|
|    PR0119269|     2026-06-22|    PL01|     MC005|     OP0125|Evening|     MTR-200|        Motors|         1182|          1226|             21|              33|    268.92|        67.94|          2.68|        Reject|              No|     Farah|
|    PR0000300|     2026-05-07|    PL01|     MC003|     OP0478|Evening|     VLV-320|        Valves|         1181|          1226|             31|              35|    359.21|         69.8|          3.13|        Reject|              No|     Farah|
|    PR0083683|     2026-04-10|    PL01|     MC002|     OP0268|Evening|     MTR-200|        Motors|         1188|          1226|             16|              45|    455.05|        59.46|          3.55|          Pass|              No|     Anita|
|    PR0022084|     2026-01-26|    PL01|     MC004|     OP0396|Morning|     PMP-310|         Pumps|         1198|          1226|             38|              15|    617.55|        69.97|          3.97|        Reject|             Yes|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [54]:
df.sort(F.col("units_produced").desc()).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0074297|     2026-05-20|    PL04|     MC019|     OP0142|Morning|     MTR-200|        Motors|         1195|          1238|             23|               0|     331.2|        66.75|           4.1|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [55]:
df.sort(F.col("downtime_minutes").desc()).show(10)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0092818|     2026-02-16|    PL06|     MC027|     OP0016|Morning|     PMP-210|         Pumps|         1066|           907|              2|             281|    359.48|        54.03|           2.8|          Pass|              No|     Farah|
|    PR0045363|     2026-07-07|    PL02|     MC010|     OP0215|  Night|     CTL-330|   Controllers|          502|           463|              3|             278|    112.25|        72.69|          4.03|          Pass|              No|    Bharat|
|    PR0020842|     2026-04-28|    PL02|     MC008|     OP0003|  Night|     MTR-200|        Motors|         1004|           985|             24|             267|    326.53|        53.78|          3.82|        Reject|              No|    Harini|
|    PR0065023|     2026-02-11|    PL06|     MC029|     OP0249|Evening|     CTL-230|   Controllers|          708|           654|             23|             267|    220.98|         67.8|           4.8|          Pass|              No|     Deepa|
|    PR0068768|     2026-03-27|    PL03|     MC012|     OP0098|  Night|     MTR-200|        Motors|          958|           898|             15|             267|     172.3|        64.62|          4.59|          Pass|              No|     Farah|
|    PR0100950|     2026-01-16|    PL03|     MC012|     OP0076|Evening|     MTR-100|        Motors|          977|           900|             13|             263|     401.3|        66.18|          1.91|          Pass|              No|    Charan|
|    PR0041129|     2026-02-06|    PL01|     MC005|     OP0338|Morning|     PMP-110|         Pumps|          374|           361|              6|             263|    158.25|        71.94|          3.47|          Pass|              No|     Gopal|
|    PR0049997|     2026-08-30|    PL04|     MC019|     OP0337|  Night|     PMP-310|         Pumps|          584|           575|              7|             263|    292.82|        42.51|          5.13|          Pass|             Yes|     Farah|
|    PR0022495|     2026-06-18|    PL05|     MC022|     OP0619|Evening|     VLV-120|        Valves|         1172|          1141|             56|             262|     265.5|        53.16|          4.48|          Pass|              No|    Charan|
|    PR0112855|     2026-03-28|    PL02|     MC008|     OP0589|Morning|     MTR-100|        Motors|          319|           269|              2|             261|     92.92|         69.9|          2.57|          Pass|             Yes|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 10 rows

In [56]:
df.sort(F.col("vibration_mm_s").desc()).select("machine_id","vibration_mm_s").show()

+----------+--------------+
|machine_id|vibration_mm_s|
+----------+--------------+
|     MC012|          8.56|
|     MC030|          8.25|
|     MC027|          7.85|
|     MC010|           7.8|
|     MC018|          7.79|
|     MC024|          7.77|
|     MC015|          7.76|
|     MC027|          7.75|
|     MC015|          7.67|
|     MC016|          7.63|
|     MC007|          7.61|
|     MC010|          7.59|
|     MC027|          7.58|
|     MC017|          7.52|
|     MC021|           7.5|
|     MC021|           7.5|
|     MC004|          7.48|
|     MC027|          7.47|
|     MC025|          7.46|
|     MC019|          7.45|
+----------+--------------+
only showing top 20 rows

**8. Aggregations**

In [58]:
df.agg(
    F.sum("units_planned").alias("total_planned"),
    F.sum("units_produced").alias("total_produced"),
    F.sum("defective_units").alias("total_defects"),
    F.avg("units_produced").alias("average_production"),
    F.max("units_produced").alias("maximum_production"),
    F.min("units_produced").alias("minimum_production"),
    F.avg("downtime_minutes").alias("average_downtime"),
    F.sum("energy_kwh").alias("total_energy"),
    F.avg("temperature_c").alias("average_temperature"),
    F.avg("vibration_mm_s").alias("average_vibration")
).show()

+-------------+--------------+-------------+------------------+------------------+------------------+-----------------+--------------------+-------------------+-----------------+
|total_planned|total_produced|total_defects|average_production|maximum_production|minimum_production| average_downtime|        total_energy|average_temperature|average_vibration|
+-------------+--------------+-------------+------------------+------------------+------------------+-----------------+--------------------+-------------------+-----------------+
|     87094621|      80927888|      2030244| 674.3990666666666|              1245|               205|33.93149474428351|2.8368014080000117E7| 63.021532392167266|3.398737691604917|
+-------------+--------------+-------------+------------------+------------------+------------------+-----------------+--------------------+-------------------+-----------------+

9.groupBy()

In [60]:
from pyspark.sql.functions import col

In [62]:
df.groupby("plant_id").agg(
    F.sum(col("units_produced")).alias("total_production_by_plant"),
).orderBy(col("total_production_by_plant").desc()).show()

+--------+-------------------------+
|plant_id|total_production_by_plant|
+--------+-------------------------+
|    PL03|                 13547769|
|    PL02|                 13546452|
|    PL04|                 13529935|
|    PL06|                 13492337|
|    PL01|                 13488232|
|    PL05|                 13323163|
+--------+-------------------------+

In [63]:
df.groupby("product_family").agg(
    F.sum(col("units_produced")).alias("total_production_by_product_family"),
).orderBy(col("total_production_by_product_family").desc()).show()

+--------------+----------------------------------+
|product_family|total_production_by_product_family|
+--------------+----------------------------------+
|        Valves|                          20433082|
|         Pumps|                          20208739|
|   Controllers|                          20168572|
|        Motors|                          20117495|
+--------------+----------------------------------+

In [64]:
df.groupby("plant_id").agg(
    F.sum(col("defective_units")).alias("total_defects_by_plant"),
).orderBy(col("total_defects_by_plant").desc()).show()

+--------+----------------------+
|plant_id|total_defects_by_plant|
+--------+----------------------+
|    PL01|                339720|
|    PL02|                339647|
|    PL03|                339264|
|    PL06|                338993|
|    PL04|                338118|
|    PL05|                334502|
+--------+----------------------+

In [66]:
df.groupby("shift").agg(
    F.avg(col("downtime_minutes")).alias("avg_downtime_by_shift"),
).orderBy(col("avg_downtime_by_shift").desc()).show()

+-------+---------------------+
|  shift|avg_downtime_by_shift|
+-------+---------------------+
|Evening|     34.2213017151833|
|  Night|   33.953058820580935|
|Morning|    33.61973080530278|
+-------+---------------------+

In [68]:
df.groupby("product_family").agg(
    F.avg(col("energy_kwh")).alias("avg_energy_usage_by_product_family"),
).orderBy(col("avg_energy_usage_by_product_family").desc()).show()

+--------------+----------------------------------+
|product_family|avg_energy_usage_by_product_family|
+--------------+----------------------------------+
|        Motors|                237.21818224597516|
|         Pumps|                236.89137927582252|
|        Valves|                236.34508750495314|
|   Controllers|                235.15370433333288|
+--------------+----------------------------------+

In [71]:
df.groupby("quality_status").agg(
    F.count(col("production_id")).alias("production_count_by_quality_status"),
).orderBy(col("production_count_by_quality_status").desc()).show()

+--------------+----------------------------------+
|quality_status|production_count_by_quality_status|
+--------------+----------------------------------+
|          Pass|                             74328|
|        Rework|                             22928|
|        Reject|                             22744|
+--------------+----------------------------------+

In [72]:
df.groupby("plant_id","shift").agg(
    F.count(col("production_id")).alias("production_count_by_plant_and_shift"),
).orderBy(col("production_count_by_plant_and_shift").desc()).show()

+--------+-------+-----------------------------------+
|plant_id|  shift|production_count_by_plant_and_shift|
+--------+-------+-----------------------------------+
|    PL03|  Night|                               6790|
|    PL02|  Night|                               6788|
|    PL02|Morning|                               6768|
|    PL06|  Night|                               6758|
|    PL01|  Night|                               6745|
|    PL04|Evening|                               6715|
|    PL04|Morning|                               6703|
|    PL03|Evening|                               6672|
|    PL01|Evening|                               6668|
|    PL04|  Night|                               6661|
|    PL01|Morning|                               6629|
|    PL05|Evening|                               6628|
|    PL06|Evening|                               6601|
|    PL05|Morning|                               6600|
|    PL03|Morning|                               6589|
|    PL02|Evening|                               6579|
|    PL05|  Night|                               6565|
|    PL06|Morning|                               6541|
+--------+-------+-----------------------------------+

In [74]:
df.groupby("plant_id","product_family").agg(
    F.count(col("defective_units")).alias("defects_by_plant_and_product_family"),
).orderBy(col("defects_by_plant_and_product_family").desc()).show()

+--------+--------------+-----------------------------------+
|plant_id|product_family|defects_by_plant_and_product_family|
+--------+--------------+-----------------------------------+
|    PL01|        Valves|                               5128|
|    PL04|        Valves|                               5125|
|    PL03|        Valves|                               5075|
|    PL02|        Valves|                               5057|
|    PL06|   Controllers|                               5055|
|    PL01|         Pumps|                               5055|
|    PL02|   Controllers|                               5050|
|    PL04|        Motors|                               5026|
|    PL03|         Pumps|                               5020|
|    PL02|         Pumps|                               5016|
|    PL06|        Valves|                               5014|
|    PL02|        Motors|                               5012|
|    PL05|        Motors|                               5005|
|    PL03|   Controllers|                               4998|
|    PL04|   Controllers|                               4992|
|    PL01|   Controllers|                               4982|
|    PL05|         Pumps|                               4980|
|    PL06|         Pumps|                               4958|
|    PL03|        Motors|                               4958|
|    PL04|         Pumps|                               4936|
+--------+--------------+-----------------------------------+
only showing top 20 rows

In [75]:
df.groupby("machine_id").agg(
    F.avg(col("temperature_c")).alias("avg_temperature_by_machine"),
).orderBy(col("avg_temperature_by_machine").desc()).show()

+----------+--------------------------+
|machine_id|avg_temperature_by_machine|
+----------+--------------------------+
|     MC019|        63.266223444138944|
|     MC020|         63.22489208633087|
|     MC029|         63.13119731057668|
|     MC009|          63.1252779855396|
|     MC014|        63.114309957574186|
|     MC023|        63.109051746112684|
|     MC027|        63.099668282725126|
|     MC022|         63.09403431245128|
|     MC015|         63.09026488395557|
|     MC001|          63.0778733146782|
|     MC017|         63.07674442190667|
|     MC011|        63.060230414746606|
|     MC007|           63.037661716587|
|     MC016|         63.03639870582378|
|     MC026|         63.02672521957329|
|     MC021|         63.01464069491981|
|     MC005|        62.979236446933044|
|     MC028|         62.97779683034558|
|     MC030|         62.96733774497327|
|     MC024|         62.96457946271644|
+----------+--------------------------+
only showing top 20 rows

In [76]:
df.orderBy("supervisor").agg(
    F.count(col("production_id")).alias("production_count_by_supervisor"),
).orderBy(col("production_count_by_supervisor").desc()).show()

+------------------------------+
|production_count_by_supervisor|
+------------------------------+
|                        120000|
+------------------------------+

**10. Joining DataFrames**

In [77]:
plant_df = spark.read.csv(
"plant_master.csv",
    header=True,
    inferSchema=True
)
machine_df = spark.read.csv(
"machine_master.csv",
    header=True,
    inferSchema=True
)

In [78]:
joined_plant = df.join(
    plant_df,
    on="plant_id",
    how="inner"
)

joined_plant.show()

+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
|plant_id|production_id|production_date|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|     plant_name|     city|region|year_opened|plant_manager|
+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
|    PL03|    PR0000001|     2026-08-07|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL04|    PR0000002|     2026-08-03|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL01|    PR0000003|     2026-05-20|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL03|    PR0000004|     2026-01-15|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL04|    PR0000005|     2026-09-21|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL01|    PR0000006|     2026-09-03|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL02|    PR0000007|     2026-05-07|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL02|    PR0000008|     2026-08-17|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL03|    PR0000009|     2026-03-10|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL02|    PR0000010|     2026-02-13|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL03|    PR0000011|     2026-09-29|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL06|    PR0000012|     2026-07-10|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|  Kolkata Plant|  Kolkata|  East|       2020|  D. Banerjee|
|    PL06|    PR0000013|     2026-07-19|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|  Kolkata Plant|  Kolkata|  East|       2020|  D. Banerjee|
|    PL03|    PR0000014|     2026-05-05|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL02|    PR0000015|     2026-03-15|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL04|    PR0000016|     2026-03-03|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL03|    PR0000017|     2026-08-04|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL03|    PR0000018|     2026-01-30|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL01|    PR0000019|     2026-01-11|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL03|    PR0000020|     2026-02-18|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
only showing top 20 rows

In [79]:

joined_plant.select(
    "production_id",
    "plant_name",
    "units_produced"
).show()

+-------------+---------------+--------------+
|production_id|     plant_name|units_produced|
+-------------+---------------+--------------+
|    PR0000001|  Chennai Plant|           993|
|    PR0000002|    Noida Plant|           836|
|    PR0000003|Hyderabad Plant|           380|
|    PR0000004|  Chennai Plant|           720|
|    PR0000005|    Noida Plant|           296|
|    PR0000006|Hyderabad Plant|           795|
|    PR0000007|     Pune Plant|           955|
|    PR0000008|     Pune Plant|           895|
|    PR0000009|  Chennai Plant|           289|
|    PR0000010|     Pune Plant|           527|
|    PR0000011|  Chennai Plant|           512|
|    PR0000012|  Kolkata Plant|           968|
|    PR0000013|  Kolkata Plant|           867|
|    PR0000014|  Chennai Plant|           456|
|    PR0000015|     Pune Plant|          1042|
|    PR0000016|    Noida Plant|           732|
|    PR0000017|  Chennai Plant|           963|
|    PR0000018|  Chennai Plant|           469|
|    PR0000019|Hyderabad Plant|           380|
|    PR0000020|  Chennai Plant|           573|
+-------------+---------------+--------------+
only showing top 20 rows

In [80]:

joined_machine = df.join(
    machine_df,
    on="machine_id",
    how="inner"
)

joined_machine.show()

+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|     MC011|    PR0000001|     2026-08-07|    PL03|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|    PL03|         CNC|              100|          2025|
|     MC019|    PR0000002|     2026-08-03|    PL04|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    PL04|     Welding|               80|          2021|
|     MC002|    PR0000003|     2026-05-20|    PL01|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|    PL01|    Assembly|               80|          2024|
|     MC013|    PR0000004|     2026-01-15|    PL03|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|    PL03|     Casting|              180|          2020|
|     MC020|    PR0000005|     2026-09-21|    PL04|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    PL04|     Testing|              120|          2018|
|     MC002|    PR0000006|     2026-09-03|    PL01|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|    PL01|    Assembly|               80|          2024|
|     MC007|    PR0000007|     2026-05-07|    PL02|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|    PL02|    Assembly|              100|          2022|
|     MC009|    PR0000008|     2026-08-17|    PL02|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|    PL02|     Welding|               80|          2020|
|     MC015|    PR0000009|     2026-03-10|    PL03|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    PL03|     Testing|              180|          2018|
|     MC006|    PR0000010|     2026-02-13|    PL02|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|    PL02|         CNC|              100|          2021|
|     MC012|    PR0000011|     2026-09-29|    PL03|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|    PL03|    Assembly|              180|          2025|
|     MC030|    PR0000012|     2026-07-10|    PL06|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|    PL06|     Testing|              150|          2021|
|     MC027|    PR0000013|     2026-07-19|    PL06|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    PL06|    Assembly|              150|          2020|
|     MC013|    PR0000014|     2026-05-05|    PL03|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|    PL03|     Casting|              180|          2020|
|     MC007|    PR0000015|     2026-03-15|    PL02|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|    PL02|    Assembly|              100|          2022|
|     MC020|    PR0000016|     2026-03-03|    PL04|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    PL04|     Testing|              120|          2018|
|     MC011|    PR0000017|     2026-08-04|    PL03|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|    PL03|         CNC|              100|          2025|
|     MC012|    PR0000018|     2026-01-30|    PL03|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|    PL03|    Assembly|              180|          2025|
|     MC005|    PR0000019|     2026-01-11|    PL01|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|    PL01|     Testing|              150|          2022|
|     MC014|    PR0000020|     2026-02-18|    PL03|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|    PL03|     Welding|              180|          2021|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
only showing top 20 rows

In [82]:
full_df = df.join(
    plant_df, "plant_id", "left"
).join(
    machine_df, "machine_id", "left"
)

In [83]:

full_df.groupBy("city").agg(
    F.sum("units_produced").alias("total")
).show()

+---------+--------+
|     city|   total|
+---------+--------+
|  Chennai|13547769|
|Ahmedabad|13323163|
|  Kolkata|13492337|
|    Noida|13529935|
|     Pune|13546452|
|Hyderabad|13488232|
+---------+--------+

In [84]:
full_df.groupBy("machine_type").agg(
    F.avg("downtime_minutes").alias("avg_downtime")
).show()

+------------+-----------------+
|machine_type|     avg_downtime|
+------------+-----------------+
|         CNC|33.64548129466162|
|     Testing|33.87585594724829|
|     Welding|34.00449382099613|
|    Assembly|33.96718284443325|
|     Casting| 34.1660783396419|
+------------+-----------------+

In [86]:
full_df.groupBy("region").agg(
    F.sum("defective_units").alias("defects")
).show()

+------+-------+
|region|defects|
+------+-------+
| South| 678984|
|  East| 338993|
|  West| 674149|
| North| 338118|
+------+-------+

In [87]:
df.join(
    machine_df,
    on="machine_id",
    how="left_anti"
).show()

+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|machine_id|production_id|production_date|plant_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

In [88]:
left_df = df.join(
    machine_df,
    on="machine_id",
    how="left"
)

left_df.filter(
    F.col("machine_type").isNull()
).show()

+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+

In [89]:
full_df.groupBy("plant_name").agg(
    F.sum("energy_kwh").alias("total_energy")
).show()

+---------------+-----------------+
|     plant_name|     total_energy|
+---------------+-----------------+
|    Noida Plant|4746238.580000002|
|  Kolkata Plant|4723180.160000009|
|  Chennai Plant|4742748.169999995|
|     Pune Plant|4757984.949999988|
|Hyderabad Plant|4725471.189999996|
|Ahmedabad Plant| 4672391.03000001|
+---------------+-----------------+

**11. Updating Data**

In [90]:
updated_df = df

In [91]:
updated_df = updated_df.withColumn(
    "quality_status",
    F.when(
        F.col("quality_status") == "Reject", "Failed"
    ).when(
        F.col("quality_status") == "Rework",
        "Requires Review"
    ).otherwise(F.col("quality_status"))
)

In [92]:
updated_df = updated_df.withColumn(
    "units_planned",
    F.when(
        F.col("product_family") == "Motors",
        F.col("units_planned") * 1.05
    ).otherwise(F.col("units_planned"))
)

In [93]:
updated_df = updated_df.withColumn(
    "energy_kwh",
    F.when(
        F.col("shift") == "Night",
        F.col("energy_kwh") * 1.03
    ).otherwise(F.col("energy_kwh"))
)

In [94]:
updated_df = updated_df.withColumn(
    "operator_id",
    F.when(
        F.col("operator_id").isNull() |
        (F.trim(F.col("operator_id")) == ""),
        "UNASSIGNED"
    ).otherwise(F.col("operator_id"))
)

In [95]:
updated_df = updated_df.withColumn(
    "supervisor",
    F.when(
        F.col("supervisor") == "Anita",
        "Anita Rao"
    ).otherwise(F.col("supervisor"))
)

In [97]:
updated_df = updated_df.withColumn(
    "corrected_temperature",
    F.round("temperature_c", 1)
)

updated_df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+----------+-------------+--------------+---------------+----------------+----------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|corrected_temperature|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+----------+-------------+--------------+---------------+----------------+----------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|            1113.0|           993|             30|              34|    388.11|         61.4|          3.88|Requires Review|              No|    Charan|                 61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|             809.0|           836|              0|               0|    398.58|        64.37|          2.28|         Failed|              No|     Farah|                 64.4|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|             464.1|           380|             17|              15|    183.34|        54.13|          4.66|         Failed|              No|     Deepa|                 54.1|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|             787.0|           720|              7|              39|    217.61|        64.47|          NULL|Requires Review|              No|     Farah|                 64.5|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|             344.0|           296|              7|              49|    115.47|        72.59|          3.21|           Pass|              No|     Deepa|                 72.6|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|1005.9000000000001|           795|             50|              44|    290.26|        64.91|          2.77|Requires Review|              No|     Gopal|                 64.9|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|            1165.0|           955|             10|               5|    355.56|        62.76|          2.89|           Pass|              No|     Gopal|                 62.8|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|             862.0|           895|             51|              77|  274.0418|         57.1|          1.34|         Failed|              No|     Irfan|                 57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|             313.0|           289|              8|              16|     87.62|        66.55|          3.07|           Pass|             Yes| Anita Rao|                 66.6|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|             532.0|           527|             26|              64|    112.17|        60.96|          3.48|         Failed|              No|     Gopal|                 61.0|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|             577.0|           512|             14|              32|    130.81|        52.81|          3.46|           Pass|              No|    Bharat|                 52.8|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|             980.0|           968|             23|              38|    377.97|        69.79|          3.43|Requires Review|              No|     Gopal|                 69.8|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|            1004.0|           867|             27|              66|  400.2683|        50.88|           5.7|           Pass|             Yes|     Deepa|                 50.9|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|             448.0|           456|              6|               6|    108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|                 67.2|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|            1140.3|          1042|              4|             172|    239.64|        76.39|          2.81|           Pass|              No|     Deepa|                 76.4|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|             870.0|           732|              0|              13|    289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|                 44.9|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|            1152.0|           963|             28|              91|    347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|                 75.1|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors| 568.0500000000001|           469|             18|              36|    241.05|        59.91|          3.87|           Pass|              No|     Farah|                 59.9|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|             381.0|           380|             16|              25|    137.99|        62.23|          4.29|           Pass|              No|     Deepa|                 62.2|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|             646.0|           573|             13|              64|    277.73|        76.92|          2.35|           Pass|              No|     Irfan|                 76.9|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+----------+-------------+--------------+---------------+----------------+----------+---------------------+
only showing top 20 rows

12. Null Values and na Functions

In [98]:
df.filter(
    F.col("operator_id").isNull() |
    (F.trim(F.col("operator_id")) == "")
).count()

1524

In [100]:
df.filter(F.col("temperature_c").isNull()).count()

2132

In [101]:
df.filter(F.col("vibration_mm_s").isNull()).count()

1788

In [102]:
df.filter(F.col("downtime_minutes").isNull()).count()

1177

In [103]:
df.na.drop().show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
|    PR0000021|     2026-05-08|    PL02|     MC010|     OP0362|Evening|     PMP-310|         Pumps|         1135|           994|             22|              47|    503.54|        61.64|          2.81|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [105]:
df.na.drop(subset=["temperature_c"]).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [106]:
df.na.fill({"downtime_minutes": 0}).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [107]:
clean_df = df.withColumn(
    "operator_id",
    F.when(
        F.col("operator_id").isNull() |
        (F.trim(F.col("operator_id")) == ""),
        "UNKNOWN"
    ).otherwise(F.col("operator_id"))
)

In [109]:
avg_temp = df.select(
    F.avg("temperature_c")
).first()[0]

clean_df = clean_df.na.fill({
    "temperature_c": avg_temp
})

In [110]:
print("Before:", df.count())
print("After:", clean_df.count())

Before: 120000
After: 120000

13. Built-in Functions

In [111]:
df.select(
    F.upper("product_family").alias("upper_family")
).show()

+------------+
|upper_family|
+------------+
|      MOTORS|
| CONTROLLERS|
|      MOTORS|
|       PUMPS|
|       PUMPS|
|      MOTORS|
|      VALVES|
|      VALVES|
| CONTROLLERS|
| CONTROLLERS|
|       PUMPS|
| CONTROLLERS|
| CONTROLLERS|
|      VALVES|
|      MOTORS|
| CONTROLLERS|
| CONTROLLERS|
|      MOTORS|
|      VALVES|
|       PUMPS|
+------------+
only showing top 20 rows

In [112]:
df.select(
    F.lower("supervisor").alias("lower_supervisor")
).show()

+----------------+
|lower_supervisor|
+----------------+
|          charan|
|           farah|
|           deepa|
|           farah|
|           deepa|
|           gopal|
|           gopal|
|           irfan|
|           anita|
|           gopal|
|          bharat|
|           gopal|
|           deepa|
|           deepa|
|           deepa|
|           irfan|
|           gopal|
|           farah|
|           deepa|
|           irfan|
+----------------+
only showing top 20 rows

In [113]:
df.select(
    F.trim("operator_id").alias("clean_operator")
).show()

+--------------+
|clean_operator|
+--------------+
|        OP0275|
|        OP0489|
|        OP0189|
|        OP0076|
|        OP0501|
|        OP0501|
|        OP0645|
|        OP0106|
|        OP0386|
|        OP0593|
|        OP0141|
|        OP0047|
|        OP0172|
|        OP0446|
|        OP0238|
|        OP0013|
|        OP0533|
|        OP0162|
|        OP0526|
|        OP0563|
+--------------+
only showing top 20 rows

In [114]:
df.select(
    F.length("product_code").alias("code_length")
).show()

+-----------+
|code_length|
+-----------+
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
|          7|
+-----------+
only showing top 20 rows

In [115]:
df.select(
    F.concat_ws(
        "-",
        F.col("plant_id"),
        F.col("machine_id")
    ).alias("plant_machine")
).show()

+-------------+
|plant_machine|
+-------------+
|   PL03-MC011|
|   PL04-MC019|
|   PL01-MC002|
|   PL03-MC013|
|   PL04-MC020|
|   PL01-MC002|
|   PL02-MC007|
|   PL02-MC009|
|   PL03-MC015|
|   PL02-MC006|
|   PL03-MC012|
|   PL06-MC030|
|   PL06-MC027|
|   PL03-MC013|
|   PL02-MC007|
|   PL04-MC020|
|   PL03-MC011|
|   PL03-MC012|
|   PL01-MC005|
|   PL03-MC014|
+-------------+
only showing top 20 rows

In [117]:
df.select(
    F.round("temperature_c", 1).alias("rounded_temp")
).show()

+------------+
|rounded_temp|
+------------+
|        61.4|
|        64.4|
|        54.1|
|        64.5|
|        72.6|
|        64.9|
|        62.8|
|        57.1|
|        66.6|
|        61.0|
|        52.8|
|        69.8|
|        50.9|
|        67.2|
|        76.4|
|        44.9|
|        75.1|
|        59.9|
|        62.2|
|        76.9|
+------------+
only showing top 20 rows

In [118]:
df.select(
    F.abs(
        F.col("units_planned") -
        F.col("units_produced")
    ).alias("difference")
).show()

+----------+
|difference|
+----------+
|        67|
|        27|
|        62|
|        67|
|        48|
|       163|
|       210|
|        33|
|        24|
|         5|
|        65|
|        12|
|       137|
|         8|
|        44|
|       138|
|       189|
|        72|
|         1|
|        73|
+----------+
only showing top 20 rows

In [119]:
df.select(
    F.regexp_replace(
        "production_id", "-", "_"
    ).alias("modified_id")
).show()

+-----------+
|modified_id|
+-----------+
|  PR0000001|
|  PR0000002|
|  PR0000003|
|  PR0000004|
|  PR0000005|
|  PR0000006|
|  PR0000007|
|  PR0000008|
|  PR0000009|
|  PR0000010|
|  PR0000011|
|  PR0000012|
|  PR0000013|
|  PR0000014|
|  PR0000015|
|  PR0000016|
|  PR0000017|
|  PR0000018|
|  PR0000019|
|  PR0000020|
+-----------+
only showing top 20 rows

In [120]:
df.select(
    F.substring("product_code", 1, 3).alias("code_part")
).show()

+---------+
|code_part|
+---------+
|      MTR|
|      CTL|
|      MTR|
|      PMP|
|      PMP|
|      MTR|
|      VLV|
|      VLV|
|      CTL|
|      CTL|
|      PMP|
|      CTL|
|      CTL|
|      VLV|
|      MTR|
|      CTL|
|      CTL|
|      MTR|
|      VLV|
|      PMP|
+---------+
only showing top 20 rows

In [122]:
df.select(
    F.coalesce(
        F.col("temperature_c"),
        F.lit(0)
    ).alias("temperature_value")
).show()

+-----------------+
|temperature_value|
+-----------------+
|             61.4|
|            64.37|
|            54.13|
|            64.47|
|            72.59|
|            64.91|
|            62.76|
|             57.1|
|            66.55|
|            60.96|
|            52.81|
|            69.79|
|            50.88|
|             67.2|
|            76.39|
|            44.92|
|            75.09|
|            59.91|
|            62.23|
|            76.92|
+-----------------+
only showing top 20 rows

14.
when() / otherwise()

In [123]:
category_df = df.withColumn(
    "efficiency",
    F.when(
        F.col("units_planned") != 0,
        F.col("units_produced") / F.col("units_planned") * 100
    )
)

category_df = category_df.withColumn(
    "efficiency_category",
    F.when(F.col("efficiency") >= 100, "Above Target")
     .when(F.col("efficiency") >= 95, "On Target")
     .when(F.col("efficiency") >= 85, "Below Target")
     .otherwise("Critical")
)

In [124]:
category_df = category_df.withColumn(
    "defect_category",
    F.when(F.col("defective_units") == 0, "Perfect")
     .when(F.col("defective_units") <= 10, "Normal")
     .when(F.col("defective_units") <= 25, "Attention")
     .otherwise("High Defect")
)

In [126]:
category_df = category_df.withColumn(
    "machine_condition",
    F.when(
        (F.col("temperature_c") > 75) |
        (F.col("vibration_mm_s") > 5),
        "Inspect"
    ).otherwise("Normal")
)

category_df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+------------------+-------------------+---------------+-----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|        efficiency|efficiency_category|defect_category|machine_condition|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+------------------+-------------------+---------------+-----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan| 93.67924528301886|       Below Target|    High Defect|           Normal|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|103.33745364647713|       Above Target|        Perfect|           Normal|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa| 85.97285067873304|       Below Target|      Attention|           Normal|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  91.4866581956798|       Below Target|         Normal|           Normal|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa| 86.04651162790698|       Below Target|         Normal|           Normal|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal| 82.98538622129436|           Critical|    High Defect|           Normal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal| 81.97424892703863|           Critical|         Normal|           Normal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|103.82830626450117|       Above Target|    High Defect|           Normal|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita| 92.33226837060703|       Below Target|         Normal|           Normal|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal| 99.06015037593986|          On Target|    High Defect|           Normal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat| 88.73483535528595|       Below Target|      Attention|           Normal|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal| 98.77551020408163|          On Target|      Attention|           Normal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa| 86.35458167330677|       Below Target|    High Defect|          Inspect|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|101.78571428571428|       Above Target|         Normal|           Normal|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa| 95.94843462246777|          On Target|         Normal|          Inspect|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan| 84.13793103448276|           Critical|        Perfect|           Normal|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|          83.59375|           Critical|    High Defect|          Inspect|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah| 86.69131238447319|       Below Target|      Attention|           Normal|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa| 99.73753280839895|          On Target|      Attention|           Normal|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan| 88.69969040247679|       Below Target|      Attention|          Inspect|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+------------------+-------------------+---------------+-----------------+
only showing top 20 rows

In [127]:
category_df.groupBy("efficiency_category").count().show()

category_df.groupBy("defect_category").count().show()

category_df.groupBy("machine_condition").count().show()

+-------------------+-----+
|efficiency_category|count|
+-------------------+-----+
|       Above Target|21735|
|          On Target|26825|
|       Below Target|54619|
|           Critical|16821|
+-------------------+-----+

+---------------+-----+
|defect_category|count|
+---------------+-----+
|      Attention|45745|
|        Perfect|11491|
|    High Defect|28058|
|         Normal|34706|
+---------------+-----+

+-----------------+------+
|machine_condition| count|
+-----------------+------+
|          Inspect| 15578|
|           Normal|104422|
+-----------------+------+

15. Complex JSON

In [129]:
machine_json = spark.read.option(
"multiline", "true"
).json("machine_configurations.json")

In [130]:
machine_json.printSchema()

root
 |-- capacity_per_hour: long (nullable = true)
 |-- installed_year: long (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- machine_type: string (nullable = true)
 |-- maintenance: struct (nullable = true)
 |    |-- frequency_days: long (nullable = true)
 |    |-- last_service: string (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- sensors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- active: boolean (nullable = true)
 |    |    |-- sensor: string (nullable = true)
 |    |    |-- unit: string (nullable = true)
 |-- specifications: struct (nullable = true)
 |    |-- max_temperature_c: long (nullable = true)
 |    |-- rated_power_kw: long (nullable = true)
 |    |-- vibration_limit_mm_s: double (nullable = true)

In [131]:
machine_json.select(
    "machine_id",
    "machine_type"
).show()

+----------+------------+
|machine_id|machine_type|
+----------+------------+
|     MC001|         CNC|
|     MC002|    Assembly|
|     MC003|     Casting|
|     MC004|     Welding|
|     MC005|     Testing|
|     MC006|         CNC|
|     MC007|    Assembly|
|     MC008|     Casting|
|     MC009|     Welding|
|     MC010|     Testing|
|     MC011|         CNC|
|     MC012|    Assembly|
|     MC013|     Casting|
|     MC014|     Welding|
|     MC015|     Testing|
|     MC016|         CNC|
|     MC017|    Assembly|
|     MC018|     Casting|
|     MC019|     Welding|
|     MC020|     Testing|
+----------+------------+
only showing top 20 rows

In [132]:
machine_json.select(
    "machine_id",
    "specifications.rated_power_kw"
).show()

+----------+--------------+
|machine_id|rated_power_kw|
+----------+--------------+
|     MC001|            22|
|     MC002|            22|
|     MC003|            55|
|     MC004|            22|
|     MC005|            30|
|     MC006|            30|
|     MC007|            22|
|     MC008|            55|
|     MC009|            30|
|     MC010|            55|
|     MC011|            30|
|     MC012|            55|
|     MC013|            30|
|     MC014|            30|
|     MC015|            45|
|     MC016|            30|
|     MC017|            30|
|     MC018|            30|
|     MC019|            30|
|     MC020|            15|
+----------+--------------+
only showing top 20 rows

In [134]:
machine_json.select(
    "machine_id",
    "specifications.max_temperature_c"
).show()

+----------+-----------------+
|machine_id|max_temperature_c|
+----------+-----------------+
|     MC001|               85|
|     MC002|               85|
|     MC003|               90|
|     MC004|               85|
|     MC005|               85|
|     MC006|               85|
|     MC007|               80|
|     MC008|               75|
|     MC009|               85|
|     MC010|               90|
|     MC011|               90|
|     MC012|               80|
|     MC013|               90|
|     MC014|               80|
|     MC015|               90|
|     MC016|               75|
|     MC017|               85|
|     MC018|               85|
|     MC019|               75|
|     MC020|               80|
+----------+-----------------+
only showing top 20 rows

In [136]:
machine_json.select(
    "machine_id",
    "specifications.vibration_limit_mm_s"
).show()

+----------+--------------------+
|machine_id|vibration_limit_mm_s|
+----------+--------------------+
|     MC001|                 5.0|
|     MC002|                 5.5|
|     MC003|                 4.5|
|     MC004|                 4.5|
|     MC005|                 4.5|
|     MC006|                 5.5|
|     MC007|                 4.5|
|     MC008|                 5.0|
|     MC009|                 5.5|
|     MC010|                 4.5|
|     MC011|                 6.0|
|     MC012|                 5.5|
|     MC013|                 5.0|
|     MC014|                 5.5|
|     MC015|                 4.5|
|     MC016|                 5.5|
|     MC017|                 4.5|
|     MC018|                 5.0|
|     MC019|                 5.0|
|     MC020|                 5.0|
+----------+--------------------+
only showing top 20 rows

In [138]:
machine_json.select(
    "machine_id",
    "maintenance"
).show()

+----------+----------------+
|machine_id|     maintenance|
+----------+----------------+
|     MC001|{60, 2026-01-14}|
|     MC002|{60, 2026-05-19}|
|     MC003|{45, 2026-08-28}|
|     MC004|{60, 2026-04-19}|
|     MC005|{30, 2026-05-09}|
|     MC006|{60, 2026-01-09}|
|     MC007|{30, 2026-06-26}|
|     MC008|{30, 2026-04-21}|
|     MC009|{30, 2026-08-13}|
|     MC010|{45, 2026-06-05}|
|     MC011|{30, 2026-04-04}|
|     MC012|{30, 2026-04-26}|
|     MC013|{60, 2026-08-03}|
|     MC014|{90, 2026-01-21}|
|     MC015|{30, 2026-09-02}|
|     MC016|{45, 2026-02-15}|
|     MC017|{30, 2026-06-23}|
|     MC018|{30, 2026-03-27}|
|     MC019|{30, 2026-07-27}|
|     MC020|{45, 2026-09-17}|
+----------+----------------+
only showing top 20 rows

In [139]:
machine_json.select(
    "machine_id",
    "sensors"
).show(truncate=False)

+----------+----------------------------------------------------------------------+
|machine_id|sensors                                                               |
+----------+----------------------------------------------------------------------+
|MC001     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC002     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC003     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC004     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC005     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC006     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC007     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC008     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC009     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC010     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC011     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC012     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC013     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC014     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC015     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC016     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC017     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC018     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC019     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
|MC020     |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|
+----------+----------------------------------------------------------------------+
only showing top 20 rows

In [141]:
sensor_df = machine_json.withColumn(
    "sensor",
    F.explode("sensors")
)
sensor_df.show(truncate=False)

+-----------------+--------------+----------+------------+----------------+--------+----------------------------------------------------------------------+--------------+-----------------------+
|capacity_per_hour|installed_year|machine_id|machine_type|maintenance     |plant_id|sensors                                                               |specifications|sensor                 |
+-----------------+--------------+----------+------------+----------------+--------+----------------------------------------------------------------------+--------------+-----------------------+
|120              |2022          |MC001     |CNC         |{60, 2026-01-14}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 5.0} |{true, temperature, C} |
|120              |2022          |MC001     |CNC         |{60, 2026-01-14}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 5.0} |{true, vibration, mm/s}|
|120              |2022          |MC001     |CNC         |{60, 2026-01-14}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 5.0} |{true, energy, kWh}    |
|80               |2024          |MC002     |Assembly    |{60, 2026-05-19}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 5.5} |{true, temperature, C} |
|80               |2024          |MC002     |Assembly    |{60, 2026-05-19}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 5.5} |{true, vibration, mm/s}|
|80               |2024          |MC002     |Assembly    |{60, 2026-05-19}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 5.5} |{true, energy, kWh}    |
|120              |2018          |MC003     |Casting     |{45, 2026-08-28}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{90, 55, 4.5} |{true, temperature, C} |
|120              |2018          |MC003     |Casting     |{45, 2026-08-28}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{90, 55, 4.5} |{true, vibration, mm/s}|
|120              |2018          |MC003     |Casting     |{45, 2026-08-28}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{90, 55, 4.5} |{true, energy, kWh}    |
|180              |2024          |MC004     |Welding     |{60, 2026-04-19}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 4.5} |{true, temperature, C} |
|180              |2024          |MC004     |Welding     |{60, 2026-04-19}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 4.5} |{true, vibration, mm/s}|
|180              |2024          |MC004     |Welding     |{60, 2026-04-19}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 22, 4.5} |{true, energy, kWh}    |
|150              |2022          |MC005     |Testing     |{30, 2026-05-09}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 30, 4.5} |{true, temperature, C} |
|150              |2022          |MC005     |Testing     |{30, 2026-05-09}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 30, 4.5} |{true, vibration, mm/s}|
|150              |2022          |MC005     |Testing     |{30, 2026-05-09}|PL01    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 30, 4.5} |{true, energy, kWh}    |
|100              |2021          |MC006     |CNC         |{60, 2026-01-09}|PL02    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 30, 5.5} |{true, temperature, C} |
|100              |2021          |MC006     |CNC         |{60, 2026-01-09}|PL02    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 30, 5.5} |{true, vibration, mm/s}|
|100              |2021          |MC006     |CNC         |{60, 2026-01-09}|PL02    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{85, 30, 5.5} |{true, energy, kWh}    |
|100              |2022          |MC007     |Assembly    |{30, 2026-06-26}|PL02    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{80, 22, 4.5} |{true, temperature, C} |
|100              |2022          |MC007     |Assembly    |{30, 2026-06-26}|PL02    |[{true, temperature, C}, {true, vibration, mm/s}, {true, energy, kWh}]|{80, 22, 4.5} |{true, vibration, mm/s}|
+-----------------+--------------+----------+------------+----------------+--------+----------------------------------------------------------------------+--------------+-----------------------+
only showing top 20 rows

In [142]:
sensor_df.select(
    "machine_id",
    "sensor.*"
).show()

+----------+------+-----------+----+
|machine_id|active|     sensor|unit|
+----------+------+-----------+----+
|     MC001|  true|temperature|   C|
|     MC001|  true|  vibration|mm/s|
|     MC001|  true|     energy| kWh|
|     MC002|  true|temperature|   C|
|     MC002|  true|  vibration|mm/s|
|     MC002|  true|     energy| kWh|
|     MC003|  true|temperature|   C|
|     MC003|  true|  vibration|mm/s|
|     MC003|  true|     energy| kWh|
|     MC004|  true|temperature|   C|
|     MC004|  true|  vibration|mm/s|
|     MC004|  true|     energy| kWh|
|     MC005|  true|temperature|   C|
|     MC005|  true|  vibration|mm/s|
|     MC005|  true|     energy| kWh|
|     MC006|  true|temperature|   C|
|     MC006|  true|  vibration|mm/s|
|     MC006|  true|     energy| kWh|
|     MC007|  true|temperature|   C|
|     MC007|  true|  vibration|mm/s|
+----------+------+-----------+----+
only showing top 20 rows

In [145]:
sensor_df.filter(
    (F.col("sensor.unit") == "temperature_c") &
    (F.col("sensor.active") == True)
).select(
    "machine_id",
    "sensor"
).show(truncate=False)

+----------+------+
|machine_id|sensor|
+----------+------+
+----------+------+

In [146]:
json_joined_df = df.join(
    machine_json,
    on="machine_id",
    how="left"
)

json_joined_df.show()

+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------+--------------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|capacity_per_hour|installed_year|machine_type|     maintenance|plant_id|             sensors|specifications|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------+--------------------+--------------+
|     MC011|    PR0000001|     2026-08-07|    PL03|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|              100|          2025|         CNC|{30, 2026-04-04}|    PL03|[{true, temperatu...| {90, 30, 6.0}|
|     MC019|    PR0000002|     2026-08-03|    PL04|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|               80|          2021|     Welding|{30, 2026-07-27}|    PL04|[{true, temperatu...| {75, 30, 5.0}|
|     MC002|    PR0000003|     2026-05-20|    PL01|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|               80|          2024|    Assembly|{60, 2026-05-19}|    PL01|[{true, temperatu...| {85, 22, 5.5}|
|     MC013|    PR0000004|     2026-01-15|    PL03|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|              180|          2020|     Casting|{60, 2026-08-03}|    PL03|[{true, temperatu...| {90, 30, 5.0}|
|     MC020|    PR0000005|     2026-09-21|    PL04|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|              120|          2018|     Testing|{45, 2026-09-17}|    PL04|[{true, temperatu...| {80, 15, 5.0}|
|     MC002|    PR0000006|     2026-09-03|    PL01|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|               80|          2024|    Assembly|{60, 2026-05-19}|    PL01|[{true, temperatu...| {85, 22, 5.5}|
|     MC007|    PR0000007|     2026-05-07|    PL02|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|              100|          2022|    Assembly|{30, 2026-06-26}|    PL02|[{true, temperatu...| {80, 22, 4.5}|
|     MC009|    PR0000008|     2026-08-17|    PL02|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|               80|          2020|     Welding|{30, 2026-08-13}|    PL02|[{true, temperatu...| {85, 30, 5.5}|
|     MC015|    PR0000009|     2026-03-10|    PL03|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|              180|          2018|     Testing|{30, 2026-09-02}|    PL03|[{true, temperatu...| {90, 45, 4.5}|
|     MC006|    PR0000010|     2026-02-13|    PL02|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|              100|          2021|         CNC|{60, 2026-01-09}|    PL02|[{true, temperatu...| {85, 30, 5.5}|
|     MC012|    PR0000011|     2026-09-29|    PL03|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|              180|          2025|    Assembly|{30, 2026-04-26}|    PL03|[{true, temperatu...| {80, 55, 5.5}|
|     MC030|    PR0000012|     2026-07-10|    PL06|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|              150|          2021|     Testing|{45, 2026-05-04}|    PL06|[{true, temperatu...| {75, 55, 5.5}|
|     MC027|    PR0000013|     2026-07-19|    PL06|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|              150|          2020|    Assembly|{60, 2026-07-23}|    PL06|[{true, temperatu...| {90, 55, 5.5}|
|     MC013|    PR0000014|     2026-05-05|    PL03|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|              180|          2020|     Casting|{60, 2026-08-03}|    PL03|[{true, temperatu...| {90, 30, 5.0}|
|     MC007|    PR0000015|     2026-03-15|    PL02|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|              100|          2022|    Assembly|{30, 2026-06-26}|    PL02|[{true, temperatu...| {80, 22, 4.5}|
|     MC020|    PR0000016|     2026-03-03|    PL04|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|              120|          2018|     Testing|{45, 2026-09-17}|    PL04|[{true, temperatu...| {80, 15, 5.0}|
|     MC011|    PR0000017|     2026-08-04|    PL03|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|              100|          2025|         CNC|{30, 2026-04-04}|    PL03|[{true, temperatu...| {90, 30, 6.0}|
|     MC012|    PR0000018|     2026-01-30|    PL03|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|              180|          2025|    Assembly|{30, 2026-04-26}|    PL03|[{true, temperatu...| {80, 55, 5.5}|
|     MC005|    PR0000019|     2026-01-11|    PL01|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|              150|          2022|     Testing|{30, 2026-05-09}|    PL01|[{true, temperatu...| {85, 30, 4.5}|
|     MC014|    PR0000020|     2026-02-18|    PL03|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|              180|          2021|     Welding|{90, 2026-01-21}|    PL03|[{true, temperatu...| {80, 30, 5.5}|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------+--------------------+--------------+
only showing top 20 rows

16. Union and Union ALL

In [147]:
extra_df = spark.read.csv(
"manufacturing_production_extra_12k.csv",
    header=True,
    inferSchema=True
)

In [148]:
print(df.count())

120000

In [149]:
print(extra_df.count())

12500

In [150]:
extra_aligned = extra_df.select(df.columns)

In [151]:
union_df = df.union(extra_aligned)

print(union_df.count())

132500

In [152]:
union_all_df = df.unionAll(extra_aligned)

print(union_all_df.count())

132500

In [153]:
print("Main:", df.count())
print("Extra:", extra_df.count())
print("Union:", union_df.count())
print("Union All:", union_all_df.count())

Main: 120000
Extra: 12500
Union: 132500
Union All: 132500

In [154]:
union_df.groupBy("production_id").count().filter(
    F.col("count") > 1
).show()

+-------------+-----+
|production_id|count|
+-------------+-----+
|    PR0000413|    2|
|    PR0000135|    2|
|    PR0000236|    2|
|    PR0000339|    2|
|    PR0000059|    2|
|    PR0000463|    2|
|    PR0000136|    2|
|    PR0000263|    2|
|    PR0000393|    2|
|    PR0000445|    2|
|    PR0000124|    2|
|    PR0000299|    2|
|    PR0000341|    2|
|    PR0000008|    2|
|    PR0000172|    2|
|    PR0000359|    2|
|    PR0000389|    2|
|    PR0000026|    2|
|    PR0000274|    2|
|    PR0000161|    2|
+-------------+-----+
only showing top 20 rows

In [155]:
unique_df = union_df.dropDuplicates()

unique_df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000304|     2026-07-31|    PL01|     MC004|     OP0518|Evening|     MTR-200|        Motors|          339|           288|              0|              57|     83.44|        58.53|          1.47|          Pass|              No|    Bharat|
|    PR0000408|     2026-08-07|    PL06|     MC028|     OP0616|Evening|     PMP-110|         Pumps|          814|           772|             23|              67|    305.59|        54.17|          4.68|          Pass|              No|    Charan|
|    PR0000485|     2026-10-06|    PL01|     MC001|     OP0494|Morning|     VLV-220|        Valves|          756|           695|             16|               0|    283.91|        70.56|          3.65|          Pass|             Yes|     Deepa|
|    PR0000621|     2026-05-02|    PL06|     MC027|     OP0622|Evening|     VLV-220|        Valves|          440|           370|             17|               0|    156.23|        58.35|          3.97|        Reject|              No|    Bharat|
|    PR0000699|     2026-06-06|    PL01|     MC002|     OP0555|  Night|     CTL-230|   Controllers|         1014|           875|             31|              30|    251.46|         70.3|           0.4|          Pass|              No|     Deepa|
|    PR0000901|     2026-06-26|    PL03|     MC011|     OP0212|Evening|     CTL-330|   Controllers|         1041|           871|              8|              10|    338.52|        82.76|           3.9|        Rework|             Yes|     Farah|
|    PR0000928|     2026-04-11|    PL05|     MC022|     OP0448|  Night|     CTL-130|   Controllers|         1097|           950|              9|              38|    465.35|        58.71|          4.95|        Reject|              No|    Charan|
|    PR0001046|     2026-03-22|    PL06|     MC028|     OP0398|Morning|     MTR-300|        Motors|          508|           474|             21|              36|    127.29|        59.15|          4.97|          Pass|              No|     Gopal|
|    PR0001604|     2026-08-21|    PL03|     MC011|     OP0545|Evening|     CTL-230|   Controllers|          313|           268|              0|              52|    115.27|        57.78|          4.43|          Pass|              No|    Harini|
|    PR0001616|     2026-06-11|    PL04|     MC019|     OP0281|  Night|     PMP-210|         Pumps|          344|           307|             20|              27|    116.84|        64.66|          3.06|        Rework|              No|     Deepa|
|    PR0001787|     2026-02-27|    PL02|     MC009|     OP0520|Evening|     MTR-200|        Motors|          878|           803|             16|              49|    262.41|        68.62|          4.23|        Reject|             Yes|    Bharat|
|    PR0002111|     2026-01-10|    PL06|     MC030|     OP0216|Morning|     PMP-110|         Pumps|          399|           350|             12|              17|    152.95|        66.18|          2.62|          Pass|              No|     Deepa|
|    PR0002144|     2026-01-21|    PL01|     MC002|     OP0447|Evening|     VLV-120|        Valves|          327|           272|             11|              35|     90.76|        60.29|          1.87|        Rework|              No|     Gopal|
|    PR0002226|     2026-03-04|    PL03|     MC011|     OP0575|  Night|     MTR-100|        Motors|         1134|          1147|              0|               0|    526.95|        49.78|          2.95|        Reject|             Yes|    Harini|
|    PR0002276|     2026-07-15|    PL02|     MC010|     OP0518|Morning|     CTL-130|   Controllers|         1047|           928|              4|               0|    192.77|        77.85|          2.59|        Reject|              No|    Bharat|
|    PR0002423|     2026-10-22|    PL03|     MC013|     OP0193|  Night|     PMP-210|         Pumps|         1064|          1004|             14|              34|    342.26|        48.96|          1.32|          Pass|              No|    Harini|
|    PR0002632|     2026-08-27|    PL06|     MC030|     OP0483|  Night|     PMP-210|         Pumps|          279|           244|              6|               6|      63.8|        53.44|           1.9|          Pass|             Yes|    Bharat|
|    PR0002883|     2026-09-16|    PL04|     MC019|     OP0553|Morning|     CTL-330|   Controllers|          603|           620|             25|              15|    282.94|        75.99|          4.35|        Rework|              No|     Deepa|
|    PR0002899|     2026-07-21|    PL06|     MC028|     OP0258|  Night|     MTR-200|        Motors|          790|           747|             11|              15|     340.8|        75.33|          3.71|          Pass|              No|    Harini|
|    PR0003156|     2026-04-19|    PL05|     MC025|     OP0524|Evening|     CTL-130|   Controllers|          700|           721|             22|             142|    159.02|        59.89|          4.79|          Pass|              No|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [156]:
print("Before:", union_df.count())
print("After:", unique_df.count())

Before: 132500
After: 132500

In [157]:
union_by_name = df.unionByName(extra_df)

union_by_name.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [158]:
rearranged_df = extra_df.select(
    *reversed(extra_df.columns)
)

final_union = df.unionByName(rearranged_df)

final_union.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

17. Window Functions

In [159]:
from pyspark.sql.window import Window

w = Window.partitionBy("plant_id").orderBy(
    F.col("units_produced").desc()
)

In [160]:
rank_df = df.withColumn(
    "row_number",
    F.row_number().over(w)
).withColumn(
    "rank",
    F.rank().over(w)
).withColumn(
    "dense_rank",
    F.dense_rank().over(w)
)

rank_df.select(
    "plant_id",
    "machine_id",
    "units_produced",
    "row_number",
    "rank",
    "dense_rank"
).show()

+--------+----------+--------------+----------+----+----------+
|plant_id|machine_id|units_produced|row_number|rank|dense_rank|
+--------+----------+--------------+----------+----+----------+
|    PL01|     MC003|          1239|         1|   1|         1|
|    PL01|     MC005|          1238|         2|   2|         2|
|    PL01|     MC002|          1236|         3|   3|         3|
|    PL01|     MC002|          1236|         4|   3|         3|
|    PL01|     MC002|          1236|         5|   3|         3|
|    PL01|     MC004|          1234|         6|   6|         4|
|    PL01|     MC005|          1233|         7|   7|         5|
|    PL01|     MC002|          1230|         8|   8|         6|
|    PL01|     MC002|          1229|         9|   9|         7|
|    PL01|     MC003|          1229|        10|   9|         7|
|    PL01|     MC002|          1229|        11|   9|         7|
|    PL01|     MC005|          1228|        12|  12|         8|
|    PL01|     MC005|          1228|        13|  12|         8|
|    PL01|     MC004|          1227|        14|  14|         9|
|    PL01|     MC001|          1227|        15|  14|         9|
|    PL01|     MC003|          1226|        16|  16|        10|
|    PL01|     MC005|          1226|        17|  16|        10|
|    PL01|     MC004|          1226|        18|  16|        10|
|    PL01|     MC002|          1226|        19|  16|        10|
|    PL01|     MC005|          1226|        20|  16|        10|
+--------+----------+--------------+----------+----+----------+
only showing top 20 rows

In [161]:
rank_df.filter(
    F.col("row_number") <= 5
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+----+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|row_number|rank|dense_rank|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+----+----------+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|         1|   1|         1|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|         2|   2|         2|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|         3|   3|         3|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|         4|   3|         3|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|         5|   3|         3|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|         1|   1|         1|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|         2|   2|         2|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|         3|   3|         3|
|    PR0027036|     2026-08-03|    PL02|     MC010|     OP0285|Morning|     MTR-200|        Motors|         1191|          1238|             12|              64|    583.51|         NULL|          2.95|          Pass|              No|    Charan|         4|   4|         4|
|    PR0012982|     2026-05-07|    PL02|     MC009|     OP0405|Evening|     CTL-330|   Controllers|         1194|          1237|              4|               0|    275.64|        68.43|          5.18|          Pass|              No|    Bharat|         5|   5|         5|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|         1|   1|         1|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|         2|   2|         2|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|         3|   2|         2|
|    PR0102987|     2026-07-07|    PL03|     MC015|     OP0220|Morning|     PMP-310|         Pumps|         1192|          1236|             10|               1|    304.23|        71.75|          3.49|          Pass|              No|     Farah|         4|   4|         3|
|    PR0021534|     2026-06-14|    PL03|     MC011|     OP0042|  Night|     MTR-100|        Motors|         1189|          1235|             46|              53|    507.11|        60.86|          1.71|          Pass|             Yes|    Charan|         5|   5|         4|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|         1|   1|         1|
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|         2|   1|         1|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|         3|   3|         2|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|         4|   4|         3|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|         5|   5|         4|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+----+----------+
only showing top 20 rows

In [162]:
machine_output = df.groupBy(
    "plant_id",
    "machine_id"
).agg(
    F.sum("units_produced").alias("total_output")
)

machine_window = Window.partitionBy(
    "plant_id"
).orderBy(
    F.col("total_output").desc(),
    F.col("machine_id")
)

machine_output.withColumn(
    "rn",
    F.row_number().over(machine_window)
).filter(
    F.col("rn") <= 3
).show()

+--------+----------+------------+---+
|plant_id|machine_id|total_output| rn|
+--------+----------+------------+---+
|    PL01|     MC004|     2722412|  1|
|    PL01|     MC002|     2713779|  2|
|    PL01|     MC001|     2691431|  3|
|    PL02|     MC009|     2760070|  1|
|    PL02|     MC007|     2713038|  2|
|    PL02|     MC008|     2705850|  3|
|    PL03|     MC012|     2750570|  1|
|    PL03|     MC015|     2739284|  2|
|    PL03|     MC014|     2735500|  3|
|    PL04|     MC016|     2750780|  1|
|    PL04|     MC019|     2735839|  2|
|    PL04|     MC017|     2726300|  3|
|    PL05|     MC024|     2737331|  1|
|    PL05|     MC023|     2718075|  2|
|    PL05|     MC022|     2635629|  3|
|    PL06|     MC026|     2723306|  1|
|    PL06|     MC027|     2718877|  2|
|    PL06|     MC030|     2701993|  3|
+--------+----------+------------+---+

In [163]:
plant_window = Window.partitionBy("plant_id")

df.withColumn(
    "plant_total",
    F.sum("units_produced").over(plant_window)
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_total|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|   13546452|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|   13546452|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|   13546452|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|   13546452|
|    PR0000021|     2026-05-08|    PL02|     MC010|     OP0362|Evening|     PMP-310|         Pumps|         1135|           994|             22|              47|    503.54|        61.64|          2.81|          Pass|              No|     Deepa|   13546452|
|    PR0000022|     2026-03-03|    PL02|     MC009|     OP0294|Evening|     MTR-300|        Motors|          623|           560|             23|              14|    217.69|        55.23|          3.28|        Reject|             Yes|     Farah|   13546452|
|    PR0000038|     2026-02-23|    PL02|     MC008|     OP0114|  Night|     MTR-300|        Motors|          864|           867|              6|              38|    335.24|         53.7|           3.0|          Pass|              No|     Anita|   13546452|
|    PR0000041|     2026-05-14|    PL02|     MC009|     OP0192|Morning|     PMP-310|         Pumps|          711|           664|             32|              60|    335.84|        57.87|           3.2|          Pass|             Yes|     Irfan|   13546452|
|    PR0000043|     2026-10-04|    PL02|     MC006|     OP0060|  Night|     VLV-120|        Valves|          306|           251|              7|              45|     80.09|         53.6|          1.84|        Rework|              No|    Harini|   13546452|
|    PR0000044|     2026-07-20|    PL02|     MC008|     OP0062|  Night|     CTL-230|   Controllers|         1086|           951|             27|              84|    477.74|        70.09|          3.32|          Pass|              No|    Bharat|   13546452|
|    PR0000058|     2026-09-12|    PL02|     MC010|     OP0079|Morning|     VLV-120|        Valves|          308|           279|              2|              46|     59.97|        52.63|           4.0|        Reject|              No|     Irfan|   13546452|
|    PR0000069|     2026-07-01|    PL02|     MC009|     OP0181|Evening|     VLV-120|        Valves|          588|           495|             15|              74|     246.2|        54.04|          4.18|          Pass|              No|    Harini|   13546452|
|    PR0000073|     2026-10-16|    PL02|     MC010|     OP0580|Evening|     PMP-210|         Pumps|          973|           979|             13|              13|    475.51|        62.22|          5.32|        Rework|              No|    Harini|   13546452|
|    PR0000082|     2026-04-22|    PL02|     MC009|     OP0479|  Night|     VLV-320|        Valves|          337|           333|             17|               8|     68.54|        63.69|          2.12|        Reject|              No|    Bharat|   13546452|
|    PR0000108|     2026-03-13|    PL02|     MC007|     OP0528|  Night|     PMP-110|         Pumps|          811|           831|             21|               4|    418.46|        56.68|          4.14|        Reject|              No|     Irfan|   13546452|
|    PR0000109|     2026-06-26|    PL02|     MC009|       NULL|Evening|     VLV-320|        Valves|          939|           918|             16|              42|    222.95|        61.35|          0.98|          Pass|              No|     Deepa|   13546452|
|    PR0000110|     2026-07-07|    PL02|     MC008|     OP0598|Evening|     CTL-130|   Controllers|          628|           549|              5|              65|    213.65|        77.27|          2.73|        Rework|              No|     Deepa|   13546452|
|    PR0000111|     2026-05-23|    PL02|     MC010|     OP0387|  Night|     MTR-200|        Motors|          929|           920|             32|              33|    275.51|        73.57|          3.14|        Rework|              No|     Gopal|   13546452|
|    PR0000118|     2026-01-15|    PL02|     MC006|     OP0085|  Night|     MTR-100|        Motors|          358|           310|              0|              13|    117.46|        60.85|          4.09|        Rework|             Yes|     Gopal|   13546452|
|    PR0000119|     2026-08-14|    PL02|     MC007|     OP0339|  Night|     MTR-200|        Motors|         1055|          1014|             20|              53|    515.92|        71.55|          3.19|        Rework|              No|    Charan|   13546452|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
only showing top 20 rows

In [164]:
machine_avg_window = Window.partitionBy("machine_id")

df.withColumn(
    "machine_avg",
    F.avg("units_produced").over(machine_avg_window)
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|      machine_avg|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|672.7265741199801|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|672.7265741199801|
|    PR0000039|     2026-07-17|    PL01|     MC002|     OP0220|  Night|     VLV-120|        Valves|          260|           265|              0|               2|    127.18|        51.87|          3.41|          Pass|              No|     Irfan|672.7265741199801|
|    PR0000063|     2026-02-18|    PL01|     MC002|     OP0390|  Night|     VLV-120|        Valves|          656|           665|              0|              44|     311.8|        58.34|           2.0|          Pass|              No|     Deepa|672.7265741199801|
|    PR0000132|     2026-03-27|    PL01|     MC002|     OP0123|Evening|     CTL-330|   Controllers|         1069|           928|             11|              11|    198.07|        64.63|          3.73|        Reject|              No|    Harini|672.7265741199801|
|    PR0000154|     2026-08-19|    PL01|     MC002|     OP0624|Morning|     PMP-310|         Pumps|          508|           450|              8|              43|    231.23|        53.02|           3.1|        Rework|              No|    Charan|672.7265741199801|
|    PR0000200|     2026-01-11|    PL01|     MC002|     OP0338|Evening|     PMP-110|         Pumps|         1146|          1051|             33|              70|    460.46|        47.92|          NULL|        Reject|              No|     Irfan|672.7265741199801|
|    PR0000233|     2026-04-20|    PL01|     MC002|     OP0437|  Night|     MTR-300|        Motors|         1084|           947|             53|              59|    404.27|        69.34|          2.31|        Reject|              No|    Charan|672.7265741199801|
|    PR0000264|     2026-07-11|    PL01|     MC002|     OP0607|Evening|     CTL-330|   Controllers|          904|           866|             12|              36|    254.73|        75.26|          4.05|          Pass|              No|    Harini|672.7265741199801|
|    PR0000268|     2026-07-24|    PL01|     MC002|     OP0537|  Night|     CTL-330|   Controllers|          668|           584|              4|               0|    217.65|        73.71|          5.29|          Pass|              No|    Harini|672.7265741199801|
|    PR0000284|     2026-01-17|    PL01|     MC002|     OP0071|Evening|     CTL-130|   Controllers|         1118|          1053|              0|              33|    485.67|        62.18|          3.95|        Reject|              No|     Irfan|672.7265741199801|
|    PR0000335|     2026-09-29|    PL01|     MC002|     OP0503|Evening|     CTL-230|   Controllers|          334|           274|              3|              22|    118.09|        67.57|          4.64|          Pass|              No|     Deepa|672.7265741199801|
|    PR0000383|     2026-10-08|    PL01|     MC002|     OP0482|Morning|     MTR-200|        Motors|          290|           244|             13|             171|     57.48|         78.1|          1.37|          Pass|              No|    Bharat|672.7265741199801|
|    PR0000402|     2026-10-22|    PL01|     MC002|     OP0516|Evening|     VLV-120|        Valves|         1150|           983|             30|              57|    264.33|        57.85|          2.94|          Pass|             Yes|    Harini|672.7265741199801|
|    PR0000405|     2026-05-14|    PL01|     MC002|     OP0308|Evening|     MTR-100|        Motors|         1170|          1127|             30|              30|    350.16|        61.28|          3.89|          Pass|             Yes|     Anita|672.7265741199801|
|    PR0000482|     2026-08-05|    PL01|     MC002|     OP0579|Evening|     MTR-200|        Motors|         1085|           925|             20|              14|    298.76|        59.72|          2.39|        Rework|              No|     Farah|672.7265741199801|
|    PR0000576|     2026-04-25|    PL01|     MC002|     OP0192|Evening|     MTR-200|        Motors|          940|           806|              0|              57|    380.36|        53.91|          2.99|          Pass|              No|     Irfan|672.7265741199801|
|    PR0000594|     2026-06-24|    PL01|     MC002|     OP0134|  Night|     PMP-110|         Pumps|          809|           815|              0|              74|    422.07|        60.19|          3.62|        Rework|             Yes|     Anita|672.7265741199801|
|    PR0000637|     2026-02-21|    PL01|     MC002|     OP0017|Evening|     PMP-310|         Pumps|          492|           448|             15|               6|    184.84|         59.1|          2.88|        Reject|              No|     Anita|672.7265741199801|
|    PR0000699|     2026-06-06|    PL01|     MC002|     OP0555|  Night|     CTL-230|   Controllers|         1014|           875|             31|              30|    251.46|         70.3|           0.4|          Pass|              No|     Deepa|672.7265741199801|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+
only showing top 20 rows

In [165]:
date_window = Window.partitionBy(
    "machine_id"
).orderBy(
    "production_date",
    "production_id"
).rowsBetween(
    Window.unboundedPreceding,
    Window.currentRow
)

df.withColumn(
    "cumulative_production",
    F.sum("units_produced").over(date_window)
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|cumulative_production|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|                  520|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|                 1180|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|                 1542|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|                 1962|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|                 2672|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|                 3501|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|                 4565|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|                 5724|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|                 5985|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|                 6838|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|                 7860|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|                 8466|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|                 9572|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|                10341|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|                11270|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|                11548|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|                12064|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|                12680|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|                13886|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|                14549|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
only showing top 20 rows

In [166]:
previous_window = Window.partitionBy(
    "machine_id"
).orderBy(
    "production_date",
    "production_id"
)

previous_df = df.withColumn(
    "previous_output",
    F.lag("units_produced", 1).over(previous_window)
)

previous_df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|previous_output|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|           NULL|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|            520|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|            660|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|            362|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|            420|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|            710|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|            829|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|           1064|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|           1159|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|            261|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|            853|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|           1022|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|            606|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|           1106|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|            769|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|            929|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|            278|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|            516|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|            616|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|           1206|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
only showing top 20 rows

In [167]:
next_df = df.withColumn(
    "next_output",
    F.lead("units_produced", 1).over(previous_window)
)

next_df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|next_output|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|        660|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|        362|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|        420|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|        710|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|        829|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|       1064|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|       1159|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|        261|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|        853|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|       1022|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|        606|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|       1106|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|        769|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|        929|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|        278|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|        516|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|        616|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|       1206|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|        663|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|        241|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
only showing top 20 rows

In [168]:
previous_df.withColumn(
    "output_change",
    F.col("units_produced") - F.col("previous_output")
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+-------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|previous_output|output_change|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+-------------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|           NULL|         NULL|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|            520|          140|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|            660|         -298|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|            362|           58|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|            420|          290|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|            710|          119|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|            829|          235|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|           1064|           95|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|           1159|         -898|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|            261|          592|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|            853|          169|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|           1022|         -416|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|            606|          500|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|           1106|         -337|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|            769|          160|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|            929|         -651|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|            278|          238|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|            516|          100|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|            616|          590|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|           1206|         -543|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+-------------+
only showing top 20 rows

In [169]:
family_df = df.groupBy("product_family").agg(
    F.sum("units_produced").alias("total_output")
)

family_window = Window.orderBy(
    F.col("total_output").desc()
)

family_df.withColumn(
    "family_rank",
    F.rank().over(family_window)
).show()

+--------------+------------+-----------+
|product_family|total_output|family_rank|
+--------------+------------+-----------+
|        Valves|    20433082|          1|
|         Pumps|    20208739|          2|
|   Controllers|    20168572|          3|
|        Motors|    20117495|          4|
+--------------+------------+-----------+

18. Date and Time Functions

In [170]:
date_df = df.withColumn(
    "production_date",
    F.to_date("production_date")
)

In [171]:
date_df = date_df.withColumn(
    "year",
    F.year("production_date")
)

In [172]:
date_df = date_df.withColumn(
    "month",
    F.month("production_date")
)

In [173]:
date_df = date_df.withColumn(
    "day",
    F.dayofmonth("production_date")
)

In [174]:
date_df = date_df.withColumn(
    "month_name",
    F.date_format("production_date", "MMMM")
)

In [175]:
date_df = date_df.withColumn(
    "day_name",
    F.date_format("production_date", "EEEE")
)

In [176]:
date_df = date_df.withColumn(
    "year_month",
    F.date_format("production_date", "yyyy-MM")
)

date_df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|2026|    9| 21| September|   Monday|   2026-09|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|2026|    9|  3| September| Thursday|   2026-09|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|2026|    9| 29| September|  Tuesday|   2026-09|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|2026|    7| 10|      July|   Friday|   2026-07|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|2026|    7| 19|      July|   Sunday|   2026-07|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
only showing top 20 rows

In [177]:
monthly_production = date_df.groupBy(
    "year_month"
).agg(
    F.sum("units_produced").alias("total_production")
).orderBy("year_month")

monthly_production.show()

+----------+----------------+
|year_month|total_production|
+----------+----------------+
|   2026-01|         8478059|
|   2026-02|         7810891|
|   2026-03|         8441121|
|   2026-04|         8211005|
|   2026-05|         8507542|
|   2026-06|         8400505|
|   2026-07|         8476416|
|   2026-08|         8529150|
|   2026-09|         8115221|
|   2026-10|         5957978|
+----------+----------------+

In [178]:
date_df.groupBy("year_month").agg(
    F.sum("defective_units").alias("total_defects")
).orderBy("year_month").show()

+----------+-------------+
|year_month|total_defects|
+----------+-------------+
|   2026-01|       211741|
|   2026-02|       197462|
|   2026-03|       212036|
|   2026-04|       208707|
|   2026-05|       212049|
|   2026-06|       210381|
|   2026-07|       210482|
|   2026-08|       214807|
|   2026-09|       202990|
|   2026-10|       149589|
+----------+-------------+

In [179]:
date_df.groupBy(
    "year_month",
    "plant_id"
).agg(
    F.sum("units_produced").alias("total")
).orderBy("year_month", "plant_id").show()

+----------+--------+-------+
|year_month|plant_id|  total|
+----------+--------+-------+
|   2026-01|    PL01|1451436|
|   2026-01|    PL02|1419252|
|   2026-01|    PL03|1429811|
|   2026-01|    PL04|1399488|
|   2026-01|    PL05|1375887|
|   2026-01|    PL06|1402185|
|   2026-02|    PL01|1342273|
|   2026-02|    PL02|1278581|
|   2026-02|    PL03|1305531|
|   2026-02|    PL04|1292557|
|   2026-02|    PL05|1324271|
|   2026-02|    PL06|1267678|
|   2026-03|    PL01|1442140|
|   2026-03|    PL02|1359740|
|   2026-03|    PL03|1416484|
|   2026-03|    PL04|1447603|
|   2026-03|    PL05|1411435|
|   2026-03|    PL06|1363719|
|   2026-04|    PL01|1350450|
|   2026-04|    PL02|1369684|
+----------+--------+-------+
only showing top 20 rows

In [180]:
date_df.filter(
    F.col("production_date").between(
        "2026-01-01",
        "2026-06-30"
    )
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02|
|    PR0000021|     2026-05-08|    PL02|     MC010|     OP0362|Evening|     PMP-310|         Pumps|         1135|           994|             22|              47|    503.54|        61.64|          2.81|          Pass|              No|     Deepa|2026|    5|  8|       May|   Friday|   2026-05|
|    PR0000022|     2026-03-03|    PL02|     MC009|     OP0294|Evening|     MTR-300|        Motors|          623|           560|             23|              14|    217.69|        55.23|          3.28|        Reject|             Yes|     Farah|2026|    3|  3|     March|  Tuesday|   2026-03|
|    PR0000024|     2026-06-07|    PL03|     MC013|     OP0456|Morning|     MTR-100|        Motors|          495|           456|              3|              14|    222.03|        67.44|          3.71|        Reject|              No|    Harini|2026|    6|  7|      June|   Sunday|   2026-06|
|    PR0000026|     2026-04-09|    PL01|     MC001|     OP0604|Evening|     MTR-300|        Motors|          643|           663|             20|              26|    180.36|        63.77|          4.49|          Pass|             Yes|    Charan|2026|    4|  9|     April| Thursday|   2026-04|
|    PR0000027|     2026-01-03|    PL05|     MC023|     OP0190|Morning|     PMP-210|         Pumps|          358|           310|              6|              46|     78.29|        75.42|          3.72|        Rework|              No|     Anita|2026|    1|  3|   January| Saturday|   2026-01|
|    PR0000029|     2026-04-30|    PL05|     MC023|     OP0339|  Night|     VLV-120|        Valves|          987|          1010|             25|              53|    199.38|        65.76|          4.48|        Reject|              No|    Harini|2026|    4| 30|     April| Thursday|   2026-04|
|    PR0000031|     2026-01-04|    PL01|     MC003|     OP0524|Evening|     PMP-210|         Pumps|          762|           776|             49|              28|    238.12|         66.8|          3.09|        Reject|              No|    Bharat|2026|    1|  4|   January|   Sunday|   2026-01|
|    PR0000032|     2026-05-28|    PL06|     MC030|     OP0074|  Night|     CTL-230|   Controllers|          819|           773|             11|              27|     354.3|        63.51|          3.18|          Pass|              No|     Deepa|2026|    5| 28|       May| Thursday|   2026-05|
|    PR0000034|     2026-04-30|    PL03|     MC015|     OP0219|Evening|     MTR-300|        Motors|         1059|          1047|              0|              32|    478.92|        68.68|          4.71|          Pass|              No|    Bharat|2026|    4| 30|     April| Thursday|   2026-04|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
only showing top 20 rows

In [181]:
date_df.withColumn(
    "after_7_days",
    F.date_add("production_date", 7)
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|after_7_days|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08|  2026-08-14|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08|  2026-08-10|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05|  2026-05-27|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01|  2026-01-22|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|2026|    9| 21| September|   Monday|   2026-09|  2026-09-28|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|2026|    9|  3| September| Thursday|   2026-09|  2026-09-10|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05|  2026-05-14|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08|  2026-08-24|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03|  2026-03-17|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02|  2026-02-20|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|2026|    9| 29| September|  Tuesday|   2026-09|  2026-10-06|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|2026|    7| 10|      July|   Friday|   2026-07|  2026-07-17|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|2026|    7| 19|      July|   Sunday|   2026-07|  2026-07-26|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05|  2026-05-12|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03|  2026-03-22|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03|  2026-03-10|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08|  2026-08-11|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01|  2026-02-06|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01|  2026-01-18|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02|  2026-02-25|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+------------+
only showing top 20 rows

In [182]:
date_df.withColumn(
    "before_30_days",
    F.date_sub("production_date", 30)
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+--------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|before_30_days|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+--------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08|    2026-07-08|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08|    2026-07-04|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05|    2026-04-20|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01|    2025-12-16|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|2026|    9| 21| September|   Monday|   2026-09|    2026-08-22|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|2026|    9|  3| September| Thursday|   2026-09|    2026-08-04|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05|    2026-04-07|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08|    2026-07-18|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03|    2026-02-08|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02|    2026-01-14|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|2026|    9| 29| September|  Tuesday|   2026-09|    2026-08-30|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|2026|    7| 10|      July|   Friday|   2026-07|    2026-06-10|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|2026|    7| 19|      July|   Sunday|   2026-07|    2026-06-19|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05|    2026-04-05|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03|    2026-02-13|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03|    2026-02-01|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08|    2026-07-05|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01|    2025-12-31|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01|    2025-12-12|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02|    2026-01-19|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+--------------+
only showing top 20 rows

In [183]:
date_df.withColumn(
    "days_difference",
    F.datediff(
        F.current_date(),
        F.col("production_date")
    )
).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+---------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|days_difference|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+---------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08|             78|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08|             82|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05|            157|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01|            282|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|2026|    9| 21| September|   Monday|   2026-09|             33|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|2026|    9|  3| September| Thursday|   2026-09|             51|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05|            170|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08|             68|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03|            228|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02|            253|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|2026|    9| 29| September|  Tuesday|   2026-09|             25|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|2026|    7| 10|      July|   Friday|   2026-07|            106|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|2026|    7| 19|      July|   Sunday|   2026-07|             97|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05|            172|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03|            223|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03|            235|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08|             81|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01|            267|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01|            286|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02|            248|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+---------------+
only showing top 20 rows

In [184]:
monthly_production.orderBy(
    F.col("total_production").desc()
).show(1)

+----------+----------------+
|year_month|total_production|
+----------+----------------+
|   2026-08|         8529150|
+----------+----------------+
only showing top 1 row